const cn = {
  /** **************** menu ***********/
  // Dashboard
  'menu.dashboard': '仪表盘',
  // Analytics
  'menu.ana': '分析',
  'menu.ana.linux_hosts': 'Linux 主机',
  'menu.ana.vmware_hosts': 'VMware 主机',
  'menu.ana.vmware_vms': 'VMware VMs',
  'menu.ana.hypervisor': 'Hypervisor',
  'menu.ana.application': '应用程序',
  'menu.ana.vm': 'VM',
  'menu.ana.physical_host': '实体主机',
  'menu.ana.infras': '基础架构',
  'menu.ana.vmware_map': 'VMware 关系图',
  'menu.ana.nutanix_hosts': 'Nutanix 主机',
  'menu.ana.nutanix_vms': 'Nutanix VMs',
  'menu.ana.windows_hosts': 'Windows 主机',
  'menu.ana.ceph_hosts': 'Ceph 主机',
  'menu.ana.ceph_clusters': 'Ceph 集群',
  'menu.ana.applications': '应用程序',
  'menu.ana.server_summary': '主机总览',
  'menu.ana.physical_machines': '实体机器',
  // Prediction
  'menu.pred': '预测',
  'menu.pred.disk_failure': '故障预测',
  'menu.pred.linux_hosts': 'Linux 主机',
  'menu.pred.vmware_hosts': 'VMware 主机',
  'menu.pred.vmware_vms': 'VMware VMs',
  'menu.pred.nutanix_hosts': 'Nutanix 主机',
  'menu.pred.nutanix_vms': 'Nutanix VMs',
  'menu.pred.windows_hosts': 'Windows 主机',
  'menu.pred.ceph_clusters': 'Ceph 集群',
  // Groups
  'menu.grp': '群组',
  'menu.grp.host': '主机群组',
  'menu.grp.disk': '磁盘群组',
  // Administration
  'menu.adm': '管理',
  'menu.adm.agents': 'Agents',
  'menu.adm.users': '用户',
  'menu.adm.audit_log': '用户操作记录',
  'menu.adm.upload': '上传',
  'menu.adm.events': '事件日志',
  'menu.adm.threshold': '定制报警',
  'menu.adm.email_settings': '邮箱通知设置',
  'menu.adm.email_server_settings': '邮箱设置',
  'menu.adm.simulation': '故障预测模拟器',
  'menu.adm.anomaly_dectect_config': '异常检测配置',

  /** ***************Common*******************/
  'common.button.save': '儲存',
  'common.button.add': '新增',
  'common.button.delete': '刪除',
  'common.button.update': '更新',
  'common.button.cancel': '取消',
  'common.button.test': '測試',
  'common.link.more': '更多',
  'common.link.less': '较少',

  'common.unit.second': '秒',

  'host_type.LINUX': 'Linux',
  'host_type.VMWARE': 'VMware',
  'host_type.NUTANIX': 'Nutanix',
  'host_type.WINDOWS': 'Windows',
  'host_type.CEPH': 'Ceph',
  'host_type.SAPHANA': 'SAP HANA',

  'common.column.critical_disk_count': '危急',
  'common.column.warngin_disk_count': '需注意',
  'common.column.normal_disk_count': '正常',
  'common.column.unknown_disk_count': '数据不足',

  'common.disk.status.bad': '危急',
  'common.disk.status.good': '正常',
  'common.disk.status.insufficient_data': '未知',
  'common.disk.status.warning': '需注意',

  'common.grid.footer.normal': '显示 {{total}} 个条目',
  'common.grid.footer.show_reduce_count': '显示 {{total}} 个条目於 {{unReduceTotal}} 个重复事件中',

  /** ***************menu.ana.ceph_clusters*******************/
  'ceph_clusters.column.cluster': '群集名称',
  'ceph_clusters.column.num_mon': 'MONs',
  'ceph_clusters.column.osds': 'OSDs',
  'ceph_clusters.column.mdss': 'MDSs',
  'ceph_clusters.column.num_pool': 'Pools',
  'ceph_clusters.column.osd_bytes_used_percentage': '集群 OSD 使用字节数 (Byte)',
  'ceph_clusters.column.health_status': '群集状态',

  /** ***************menu.adm.agents*******************/
  'agent.column.cluster_name': '集群名',
  'agent.column.heartBeat_interval': '检测间隔',
  'agent.column.host_ip_address': '主机 IP 地址',
  'agent.column.host_name': '主机名',
  'agent.column.agent_version': 'Agent 版本',
  'agent.column.last_update': '最后更新',
  'agent.column.agent_status': 'Agent 状态',
  'agent.column.agent_type': 'Agent 类型',
  'agent.column.problems': '原因',

  'sai_agent.agent_typ.ceph': 'Ceph',
  'sai_agent.agent_typ.linux': 'Linux',
  'sai_agent.agent_typ.nutanix': 'Nutanix',
  'sai_agent.agent_typ.windows': 'Windows',
  'sai_agent.agent_typ.vmware': 'VMware',
  'sai_agent.agent_typ.appdynamics': 'AppDynamics',

  /** ***************E-Mail Settings*******************/
  'page.adm.email_settings': '邮箱通知设置',
  'page.adm.email_settings.add': '添加邮箱通知设置',
  'page.adm.email_settings.edit': '修改邮箱通知设置',
  'page.adm.email_settings.delete': '删除邮箱通知设置',

  'email_settings.email_type': '类型',
  'email_settings.subject': '主题',
  'email_settings.message': '内容',
  'email_settings.to': '邮箱',
  'email_settings.description': '描述',

  'email_settings.note': '指定邮箱接收特定事件通知',
  'email_settings.subject.note': '寄發邮箱之主题；可依實際需求更新預設值。',
  'email_settings.message.note': '寄發邮箱之内容；可依實際需求更新預設值。',
  'email_settings.to.note': '指定接收接收者之邮箱；若含一個以上之邮箱，則以分號";"隔開。',
  'email_settings.description.note': '对於此邮箱设置之註解',

  'email_settings.to.placeholder': '邮箱1;邮箱2;邮箱3...',

  'validation.email_settings.subject.obligate': '主题为必填项。',
  'validation.email_settings.subject.length': '主题长度应小于1024个字符。',
  'validation.email_settings.message.length': '内容长度应小于4096字符。',
  'validation.email_settings.description.length': '描述长度应小于1024个字符。',
  'validation.email_settings.to.obligate': '邮箱为必填项。',
  'validation.email_settings.to.length': '邮箱长度应小于512个字符。',
  'validation.email_settings.from.obligate': '邮箱为必填项',
  'validation.email_settings.from.length': '邮箱长度应小于60个字符。',
  'validation.email_settings.fail': '电子邮箱设置表单中存在一些错误。',
  'validation.email_settings.email.invalid.format': '邮箱格式错误。',

  'email_settings.delete.confirm': '您确定要删除此邮箱的设置吗？',
  'email_settings.delete.success': '邮箱设置已被删除。',
  'email_settings.delete.fail.appendErrMsg': '删除邮箱设置失败，错误：{{ message }}',
  'email_settings.add.fail.appendErrMsg': '添加邮箱设置失败，错误：{{ message }}',
  'email_settings.edit.fail.appendErrMsg': '修改邮箱设置失败，错误：{{ message }}',
  'email_settings.get.fail.appendErrMsg': '无法获取邮箱的设置数据。 错误：{{ message }}',

  'email_type.METRICS_MONITORING': '硬體工作量監控事件',
  'email_type.METRICS_MONITORING.note': '違反工作量限制條件',
  'email_type.APPDYNAMICS_EVENT': 'AppDynamics 动态事件',
  'email_type.APPDYNAMICS_EVENT.note': '違反AppDynamic健康監控狀態',
  'email_type.DISK_PREDICTION': '磁盘预测',
  'email_type.DISK_PREDICTION.note': '磁盘故障预测事件',
  'email_type.LICENSE': '授杈',
  'email_type.LICENSE.note': '授杈失效通知',
  'email_type.ANOMALY_LOG': '日誌異常事件',
  'email_type.ANOMALY_LOG.note': '經日誌分析異常事件',
  'email_type.ANOMALY_METRICS': '工作量異常事件',
  'email_type.ANOMALY_METRICS.note': '經工作量分析異常事件',

  /** ***************E-Mail SMTP Server Settings*******************/
  'page.adm.email_server_settings': '邮箱设置',

  'email_server_settings.general_settings': '一般设定',
  'email_server_settings.server_settings': '邮箱服务器设定',
  'email_server_settings.default_send_to': '默認收件人',
  'email_server_settings.from': '发件人',
  'email_server_settings.smtp_host': 'SMTP 主机',
  'email_server_settings.smtp_port': 'SMTP 端口',
  'email_server_settings.authenticationRequired': '是否需要帐号认证',
  'email_server_settings.smtp_username': 'SMTP 用户名',
  'email_server_settings.smtp_password': 'SMTP 密码',
  'email_server_settings.smtp_confirm_password': '确认 SMTP 密码',
  'email_server_settings.enabled': '启用',
  'email_server_settings.try_to_connect_smtp_server': '尝试连结至SMTP服务器',
  'email_server_settings.save_and_send_test_email': '保存并寄送测试邮件',
  'email_server_settings.try_to_connect_smtp_server.successfully': '连结测试成功，如果SMTP设定合法，你将收到测试邮件。',
  'email_server_settings.save_and_send_test_email.successfully': '保存成功，如果SMTP设定合法，你将收到测试邮件。',

  'validation.email_server_settings.smtp_host.obligate': 'SMTP 主机为必填项。',
  'validation.email_server_settings.smtp_host.length': 'SMTP 主机长度应小于200个字符。',
  'validation.email_server_settings.smtp_port.obligate': 'SMTP 端口为必填项。',
  'validation.email_server_settings.smtp_port.data_type': 'SMTP 端口值必需為正數字(0 ~ 65535)。',
  'validation.email_server_settings.smtp_port.range': 'SMTP 端口值必需為 0 ~ 65535範圍中之任一數字。',
  'validation.email_server_settings.smtp_username.length': 'SMTP 用户名长度应小于200个字符。',
  'validation.email_server_settings.smtp_password.length': 'SMTP 密码长度应小于200个字符。',
  'validation.email_server_settings.smtp_confirm_password_not_equal': 'SMTP 确认密码必须等同于SMTP 密码。',

  /** ***************Events*******************/
  'event_type.ALL': '所有',
  'event_type.FIRST_AGENT_HEARTBEAT': '首次 Agent Heartbeat',
  'event_type.INTERVAL_AGENT_HEARTBEAT': '间隔 Agent Heartbeat',
  'event_type.METRICS_MONITORING': '指标监控',
  'event_type.MONITORING': '指标报警',
  'event_type.AGENT_MONITORING': 'Agent 监控',
  'event_type.DISK_FAILURE_PREDICTION': '磁盘故障预测',
  'event_type.LICENSE': '授杈',
  'event_type.ANOMALY_METRICS': '工作量異常事件',
  'event_type.APPDYNAMICS_EVENT': 'AppDynamics 事件',
  'event_type.DISKPROPHET': '磁盘故障预测事件',
  'event_type.ANOMALY_LOG': '日誌異常事件',

  'sai_event.event_type.First Agent Heartbeat': '首次 Agent Heartbeat',
  'sai_event.event_type.Interval Agent Heartbeat': '间隔 Agent Heartbeat',
  'sai_event.event_type.Metrics Monitoring': '指标监控',
  'sai_event.event_type.Metrics Alert': '指标报警',
  'sai_event.event_type.Agent Monitoring': 'Agent 监控',
  'sai_event.event_type.Disk Failure Prediction': '磁盘故障预测',
  'sai_event.event_type.License': '授杈',
  'sai_event.event_type.Anomaly Metric': '工作量異常事件',
  'sai_event.event_type.AppDynamics Event': 'AppDynamics 事件',
  'sai_event.event_type.DiskProphet': '磁盘故障预测事件',
  'sai_event.event_type.Anomaly Log': '日誌異常事件',

  'event_level.ALL': '所有',
  'event_level.DEBUG': '调试',
  'event_level.INFO': '信息',
  'event_level.WARN': '警告',
  'event_level.ERROR': '错误',
  'event_level.FATAL': '严重',

  'sai_event.event_level.Debug': '调试',
  'sai_event.event_level.Info': '信息',
  'sai_event.event_level.Warn': '警告',
  'sai_event.event_level.Error': '错误',
  'sai_event.event_level.Fatal': '严重',

  /** ***************Workload*******************/
  'workload.DISKIO_READ_BYTES': '磁盘读取吞吐量',
  'workload.DISKIO_WRITE_BYTES': '磁盘写入吞吐量',
  'workload.DISKID_READS': '磁盘读取 I/O',
  'workload.DISKIO_WRITES': '磁盘写入 I/O',
  'workload.DISKIO_READ_TIME': '磁盘读取延迟',
  'workload.DISKIO_WRITE_TIME': '磁盘写入延迟',
  'workload.NET_BYTES_RECV': '网络接收使用率',
  'workload.NET_BYTES_SENT': '网络发送使用率',
  'workload.NET_PACKETS_RECV': '网络接收数据包',
  'workload.NET_PACKETS_SENT': '网络发送数据包',
  'workload.NET_DROP_IN': '网络接收丢包',
  'workload.NET_DROP_OUT': '网络发送丢包',
  'workload.NET_ERROR_IN': '网络错误接收',
  'workload.NET_ERROR_OUT': '网络错误发送',
  'workload.CPU_USAGE_USER': 'CPU',
  'workload.MEM_USED_PERCENT': '内存使用率',
  'workload.MEM_USED': '内存使用量',
  'workload.SYSTEM_LOAD5': 'Load5',
  'workload.DISK_USED': '存储容量',

  'workload.HOSTSYSTEM_CPU_USAGE_AVERAGE': '主机 CPU',
  'workload.HOSTSYSTEM_MEM_USAGE_AVERAGE': '主机内存',
  'workload.HOSTSYSTEM_DISK_READ_AVERAGE': '主机磁盘读取吞吐量',
  'workload.HOSTSYSTEM_DISK_WRITE_AVERAGE': '主机磁盘写入吞吐量',
  'workload.HOSTSYSTEM_DATASTORE_TOTALREADLATENCY_AVERAGE': '主机磁盘读取延迟',
  'workload.HOSTSYSTEM_DATASTORE_TOTALWRITEDLATENCY_AVERAGE': '主机磁盘写入延迟',
  'workload.HOSTSYSTEM_DATASTORE_NUMBERREADAVERAGED_AVERAGE': '主机磁盘读取 I/O',
  'workload.HOSTSYSTEM_DATASTORE_NUMBERWRITEAVERAGED_AVERAGE': '主机磁盘写入 I/O',
  'workload.HOSTSYSTEM_NET_RECEIVED_AVERAGE': '主机网络接收',
  'workload.HOSTSYSTEM_NET_TRANSMITTED_AVERAGE': '主机网络传输',
  'workload.HOSTSYSTEM_NET_ERROR_IN': '主机网络错误接收',
  'workload.HOSTSYSTEM_NET_ERROR_OUT': '主机网络错误发送',
  'workload.VIRTUALMACHINE_CPU_USAGE_AVERAGE': 'VM CPU',
  'workload.VIRTUALMACHINE_MEM_USAGE_AVERAGE': 'VM 内存',
  'workload.VIRTUALMACHINE_DATASTORE_NUMBERREADAVERAGED_AVERAGE': 'VM 磁盘读取 I/O',
  'workload.VIRTUALMACHINE_DATASTORE_NUMBERWRITEAVERAGED_AVERAGE': 'VM 磁盘写入 I/O',
  'workload.VIRTUALMACHINE_DATASTORE_READ_AVERAGE': 'VM 磁盘读取吞吐量',
  'workload.VIRTUALMACHINE_DATASTORE_WRITE_AVERAGE': 'VM 磁盘写入吞吐量',
  'workload.VIRTUALMACHINE_DATASTORE_TOTALREADLATENCY_AVERAGE': 'VM 磁盘读取延迟',
  'workload.VIRTUALMACHINE_DATASTORE_TOTALWRITELATENCY_AVERAGE': 'VM 磁盘写入延迟',
  'workload.VIRTUALMACHINE_NETWORK_RECEIVED_AVERAGE': 'VM 网络接收',
  'workload.VIRTUALMACHINE_NETWORK_TRANSMITTED_AVERAGE': 'VM 网络传输',
  'workload.VIRTUALMACHINE_NETWORK_PACKETSRX_SUMMATION': 'VM 网络接收数据包',
  'workload.VIRTUALMACHINE_NETWORK_PACKETSTX_SUMMATION': 'VM 网络发送数据包',

  'workload.NUTANIX_DISKIO_READ_BYTES': '磁盘读取吞吐量',
  'workload.NUTANIX_DISKIO_WRITE_BYTES': '磁盘写入吞吐量',
  'workload.NUTANIX_DISKIO_READS': '磁盘读取 I/O',
  'workload.NUTANIX_DISKIO_WRITES': '磁盘写入 I/O',
  'workload.NUTANIX_DISKIO_READ_TIME': '磁盘读取延迟',
  'workload.NUTANIX_DISKIO_WRITE_TIME': '磁盘写入延迟',
  'workload.NUTANIX_NET_BYTES_RECV': '网络接收使用率',
  'workload.NUTANIX_NET_BYTES_SENT': '网络发送使用率',
  'workload.NUTANIX_NET_PACKETS_RECV': '网络接收数据包',
  'workload.NUTANIX_NET_PACKETS_SENT': '网络发送数据包',
  'workload.NUTANIX_NET_DROP_IN': '网络接收丢包',
  'workload.NUTANIX_NET_DROP_OUT': '网络发送丢包',
  'workload.NUTANIX_NET_ERROR_IN': '网络错误接收',
  'workload.NUTANIX_NET_ERROR_OUT': '网络错误发送',
  'workload.NUTANIX_CPU_USAGE_USER': 'CPU',
  'workload.NUTANIX_MEM_USAGE_PERCENT': '内存使用率',
  'workload.NUTANIX_SYSTEM_LOAD5': 'Load5',
  'workload.NUTANIX_VIRTUALMACHINE_CPU_USAGE_PPM': 'VM CPU',
  'workload.NUTANIX_VIRTUALMACHINE_GEST_MEM_USAGE_PPM': 'VM 内存',
  'workload.NUTANIX_VIRTUALMACHINE_DISKIO_READ_TIME': 'VM 磁盘读取延迟',
  'workload.NUTANIX_VIRTUALMACHINE_DISKIO_WRITE_TIME': 'VM 磁盘写入延迟',
  'workload.NUTANIX_VIRTUALMACHINE_DISKIO_READ': 'VM 磁盘读取 I/O',
  'workload.NUTANIX_VIRTUALMACHINE_DISK_WRITE': 'VM 磁盘写入 I/O',
  'workload.NUTANIX_VIRTUALMACHINE_DISK_READ_THROUGHPUT': 'VM 磁盘读取吞吐量',
  'workload.NUTANIX_VIRTUALMACHINE_DISK_WRITE_THROUGHPUT': 'VM 磁盘写入吞吐量',

  'workload.WIN_CPU_PERCENT_USER_TIME': 'CPU',
  'workload.WIN_MEM_PERCENT_MEMORY_USAGE': '内存使用率',
  'workload.WIN_DISK_USED_MEGABYTES': '磁盘已使用量',
  'workload.WIN_DISKIO_READ_BYTES_PERSEC': '磁盘读取 MBps',
  'workload.WIN_DISKIO_WRITE_BYTES_PERSEC': '磁盘写入 MBps',
  'workload.WIN_DISKIO_READS_PERSEC': '磁盘读取 IOps',
  'workload.WIN_DISKIO_WRITES_PERSEC': '磁盘写入 IOps',
  'workload.WIN_DISKIO_PERCENT_DISK_READ_TIME': '磁盘读取延迟百分比',
  'workload.WIN_DISKIO_PERCENT_DISK_WRITE_TIME': '磁盘写入延迟百分比',
  'workload.WIN_NET_PACKETS_RECV_PERSEC': '网络每秒接收数据包',
  'workload.WIN_NET_PACKETS_SENT_PERSEC': '网络每秒发送数据包',
  'workload.WIN_NET_BYTES_RECV_PERSEC': '网络接收使用率',
  'workload.WIN_NET_BYTES_SENT_PERSEC': '网络发送使用率',
  'workload.WIN_NET_PACKETS_DROP_IN': '网络接收丢包',
  'workload.WIN_NET_PACKETS_DROP_OUT': '网络发送丢包',
  'workload.WIN_NET_PACKETS_ERROR_IN': '网络错误接收',
  'workload.WIN_NET_PACKETS_ERROR_OUT': '网络错误发送',

  'workload.CEPH_CLUSTER_OSD_BYTES_USED_PERCENTAGE': '集群 OSD 使用字节数 (Byte)',
  'workload.CEPH_POOL_BYTES_USED': 'Pool 使用字节数 (Byte)',
  'workload.CEPH_POOL_RAW_BYTES_USED': 'Pool 原始使用字节数 (Byte)',
  'workload.CEPH_POOL_READ_BYTES': 'Pool 读取 I/O 字节数 (Byte)',
  'workload.CEPH_POOL_WRITE_BYTES': 'Pool 写入 I/O 字节数 (Byte)',
  'workload.CEPH_OSD_READS': 'OSD 读取 I/O 次数',
  'workload.CEPH_OSD_WRITES': 'OSD 写入 I/O 次数',
  'workload.CEPH_OSD_READ_TIME': 'OSD 读取 I/O 延迟 (秒)',
  'workload.CEPH_OSD_WRITE_TIME': 'OSD 写入 I/O 延迟 (秒)',
  'workload.CEPH_OSD_READ_OUT_BYTES': 'OSD 读取 I/O 字节数 (秒)',
  'workload.CEPH_OSD_WRITE_IN_BYTES': 'OSD 写入 I/O 字节数 (秒)',
  'workload.CEPH_OSD_STAT_BYTES_USED_PERCENTAGE': 'OSD 使用字节数 (Byte)',

  /** ***************Disk Failure*******************/
  'diskfailure.grid.not_support_host_type': '此主机类型目前尚不支援，無法跳轉自該主機頁面。',

  /** ***************Analytics > Applications*******************/
  'analytics.applications.grid.applications_name': '应用程序名字',
  'analytics.applications.grid.host': '主机',
  'analytics.applications.grid.host_ip': '主机 IP',
  'analytics.applications.event.grid.name': '名字',
  'analytics.applications.event.grid.level': '等级',
  'analytics.applications.event.grid.start_time': '开始时间',
  'analytics.applications.event.grid.end_time': '结束时间',

  'First Agent Heartbeat': '首次 Agent Heartbeat',
  'Interval Agent Heartbeat': '间隔 Agent Heartbeat',
  'Metrics Monitoring': '指标监控',
  'Metrics Alert': '指标报警',
  'Agent Monitoring': 'Agent 监控',
  'Disk Failure Prediction': '磁盘故障预测',
  'Disk Health Prediction': '磁盘状况预测',

  'Debug': '调试',
  'Info': '信息',
  'Warn': '警告',
  'Error': '错误',
  'Fatal': '严重',

  // Dashboard
  'Dashboard': '仪表盘',
  // Analytics
  'Analytics': '分析',
  'Linux Hosts': 'Linux 主机',
  'VMware Hosts': 'VMware 主机',
  'VMware VMs': 'VMware VMs',
  'VMware Map': 'VMware 关系图',
  'Nutanix Hosts': 'Nutanix 主机',
  'Nutanix VMs': 'Nutanix VMs',
  'Windows Hosts': 'Windows 主机',
  'Server Summary': '主机总览',
  'Time Machine': '时光机器',
  'Physical Machines': '实体机器',

  // Prediction
  'Prediction': '预测',
  'Disk Failure': '故障预测',
  // Groups
  'Groups': '群组',
  'Group': '群组',
  'Host Groups': '主机群组',
  'Disk Groups': '磁盘群组',
  // Administration
  'Administration': '管理',
  'Agents': 'Agents',
  'Users': '用户',
  'Audit Log': '用户操作记录',
  'Upload': '上传',
  'Events': '事件日志',
  'Alert Configuration': '定制报警',
  'Disk Conditioner': '故障预测模拟器',

  'Summary': '概述',
  'Agent Status': 'Agent 状态',
  'Disks': '磁盘',
  'Monitored Disk Space': '磁盘空间',
  'Critical': '危急',
  'Warning': '需注意',
  'Normal': '正常',

  // Anomaly Configuration
  'Anomaly.SubTitle': '异常配置',
  'Anomaly.selectHost': '选择主机',
  'Anomaly.Category': '类别',
  'Anomaly.Enable': '启用',
  'Anomaly.Sensitivity': '灵敏度',
  'Anomaly.SN': '序号',
  'Anomaly.OSType': 'OS 类型',
  'trueEnable': '是',
  'falseEnable': '否',
  'Low': '低',
  'Medium': '中',
  'High': '高',
  'Anomaly.Search': '请搜索并检查您要检测的主机',
  'Anomaly.LoadFaild': '加载失败：',
  'Anomaly.hostLoadFaild': '主机加载失败：',
  'Anomaly.deleted': '异常配置已被删除',
  'Anomaly.delete.Config': '删除异常配置',
  'Anomaly.sure.delete': '你确定要删除吗？',
  'Anomaly.Add.successfully': '添加成功',
  'Anomaly.Save.success': '保存成功',
  'LINUX': 'Linux',
  'VMWARE': 'VMware',
  'NUTANIX': 'Nutanix',
  'CEPH': 'Ceph',
  'WINDOWS': 'Windows',
  'LINUX_CPU': 'Linux CPU',
  'LINUX_CAPACITY': 'Linux 存储容量',
  'LINUX_DISK_PERFORMANCE': 'Linux 磁盘性能',
  'LINUX_MEMORY': 'Linux 内存',
  'LINUX_NETWORKS': 'Linux 网络',
  'LINUX_LOAD': 'Linux 加载',
  'VMWARE_HOST_CPU': 'VMware 主机 CPU',
  'VMWARE_HOST_MEMORY': 'VMware 主机内存',
  'VMWARE_HOST_NETWORKS': 'VMware 主机网络',
  'VMWARE_HOST_DISK_PERFORMANCE': 'VMware 主机磁盘性能',
  'VMWARE_VM_CPU': 'VMware VM CPU',
  'VMWARE_VM_MEMORY': 'VMware VM 内存',
  'VMWARE_VM_DISK_PERFORMANCE': 'VMware VM 磁盘性能',
  'VMWARE_VM_NETWORKS': 'VMware VM 网络',
  'NTNX_VM_CPU': 'Ntnx VM CPU',
  'NTNX_VM_DISK_PERFORMANCE': 'Ntnx VM 磁盘性能',
  'NTNX_VM_MEMORY': 'Ntnx VM 内存',
  'NTNX_HOST_CPU': 'Ntnx 主机 CPU',
  'NTNX_HOST_CAPACITY': 'Ntnx 主机容量',
  'NTNX_HOST_DISK_PERFORMANCE': 'Ntnx 主机磁盘性能',
  'NTNX_HOST_MEMORY': 'Ntnx 主机内存',
  'NTNX_HOST_NETWORKS': 'Ntnx 主机网络',
  'NTNX_HOST_LOAD': 'Ntnx 主机加载',
  'CEPH_OSD': 'Ceph OSD',
  'CEPH_POOL': 'Ceph Pool',
  'WINDOWS_CPU': 'Windows CPU',
  'WINDOWS_CAPACITY': 'Windows 容量',
  'WINDOWS_DISK_PERFORMANCE': 'Windows 磁盘性能',
  'WINDOWS_MEMORY': 'Windows 内存',
  'WINDOWS_NETWORKS': 'Windows 网络',
  // ============

  'Save/Reset Layout': '保存/重置样式',
  'Save Layout': '保存布局',
  'Reset to Default': '重置为默认',
  'Arrange': '排列',
  'Export to PDF': '导出为 PDF',
  'Export to CSV': '导出为 CSV',
  'Filter': '筛选',
  'Search for...': '搜索...',
  'Count': '数量',
  'System': '系统',
  'User': '用户',
  'Used': '已使用',
  'Cached': '已缓存',
  'Free': '未使用',
  'Load5': 'Load5',
  'ESX Memory': 'ESX 内存',
  'CPU Ready': 'CPU Ready',
  'Failure Prediction': '故障预测',
  'Health Prediction': '状况预测',
  'Needs Attention': '需注意',
  'Unknown': '未知&nbsp;',
  'Good': '正常&nbsp;',
  'Bad': '危急&nbsp;',
  'Loaded server count / Total server count': '加载服务器数量 / 服务器总数量',
  'Disk Health': '磁盘状况',
  'Total Disks': '磁盘总数',
  'Search by name': '搜索',
  'Actual': '实际',
  'Historical': '历史',
  'VMware Version': 'VMware 版本',
  'ESX Host': 'ESX 主机',
  'Datastore': '数据存储',
  'Predicted': '预计',
  'Weeks': '周',
  'Actions': '操作',
  'From': '起始',
  'To': '到',
  'From Date': '填写日期',
  'To Date': '填写日期',
  'From Time': '起始时间',
  'To Time': '结束时间',
  'Search': '搜索',
  'Refresh': '刷新 ',
  'All': '所有',
  'Log In': '登录',
  'Log Out': '退出',
  'Change Password': '更改密码',
  'Changed Password': '更改密码',
  'IP Address': 'IP 地址',
  'Action': '操作',
  'Date': '日期',
  'Status': '状态',
  'Event Type': '类型',
  'Event Level': '等级',
  'Title': '内容',
  'Agent Host': '主机',
  'Host IP': '主机 IP',
  'Type': '类型',
  'Level': '等级',
  'There is no more event in this time range': '在该时间范围内没有更多事件',
  'Event counts': '事件数量',
  'Drive Name': '硬盘驱动器名称',
  'Host Name': '主机名',
  'Confidence': '可信度',
  'Time of Prediction': '预测时间',
  'Symptom': '症状',
  'Recommended Replacement Time': '建议更换时间',
  'Serial #': '序列号',
  'Disk Vendor': '磁盘厂商',
  'Model': 'Model',
  'Temperature': '温度',
  'Sector Error Count': '扇区错误计数',
  'Max': '最大',
  'None': '无',
  'Error Correction Count': '纠错计数',
  'HW Instability (a collection of disk hardware related attributes, such as G-sense error rate, high fly writes, etc.)': '硬件不稳定（磁盘硬件相关属性，例如 G-sense 错误率，高速写入等）',
  'Historic Average Workload IO': '历史平均 I/O 负载',
  'Historic Average Workload Memory': '历史平均内存负载',
  'Simulate': '模拟',
  'Restore': '恢复',
  'processing': '处理中',
  'Host Type': '主机类型',
  'Metrics': '对象',
  'Operand': '判断',
  'alert_config_action_email_description': '选取此选项会启用邮件报警并发送邮件给默认寄件人（可于邮件设定页面设定默认寄件人）。',
  'alert_config_action_email_error': '默认寄件人尚未设定，请至邮件设定页面填入默认设定人。',
  'alert_config_rule_description': '违反指标时将会触发事件报警',
  'Default action is event': '默认以 事件日志 来表现',
  'Note': '注释',
  'Threshold': '值',
  'Disk Read Throughput': '磁盘读取吞吐量',
  'Disk Write Throughput': '磁盘写入吞吐量',
  'Disk Read IO': '磁盘读取 I/O',
  'Disk Write IO': '磁盘写入 I/O',
  'Disk Read 延迟': '磁盘读取延迟',
  'Disk Write Latency': '磁盘写入延迟',
  'Network Received Usage': '网络接收使用率',
  'Network Sent Usage': '网络发送使用率',
  'Network Received Packet': '网络接收数据包',
  'Network Sent Packet': '网络发送数据包',
  'Network Drop in': '网络接收丢包',
  'Network Drop out': '网络发送丢包',
  'Memory Used Percent': '内存使用率',
  'Memory Used': '内存使用量',
  'Capacity': '存储容量',
  'Unit': '单位',
  'Add': '添加',
  'Upload a file with .7z extenstion': '上传 .7z 文件 ',
  'Please choose a .7z file to upload': '请选择一个 .7z 文件上传',
  'Uploading': '上传中',
  'Upload successfully': '上传成功',
  'Upload failed': '上传失败',
  'Edit': '修改',
  'Role': '角色',
  'First Name': '名字',
  'Last Name': '姓',
  'Email': '邮箱',
  'Phone': '电话',
  'Agent Domain Id': 'Agent ID',
  'Cluster Domain Id': '集群 ID',
  'HeartBeat Interval': '检测间隔',
  'Host IP Address': '主机 IP 地址',
  'Agent Version': 'Agent 版本',
  'Last Update': '最后更新',
  'Last 1 hour': '最近 1小时',
  'Last 12 hours': '最近 12小时',
  'Last 1 day': '最近 1天',
  'Last 7 days': '最近 7天',
  'Last 30 days': '最近 30天',
  'Network Usage': '网络使用率',
  'Network Usage (Received)': '网络使用率 (接收)',
  'Network Usage (Sent)': '网络使用率 (发送)',
  'Network Packets (Received)': '网络数据包 (接收)',
  'Network Packets (Sent)': '网络数据包 (发送)',
  'Packet Drops (Drop In)': '丢包 (删除进)',
  'Packet Drops (Drop Out)': '丢包 (删除出)',
  'Bytes Received/sec': '字节数接收/秒',
  'Bytes Sent/sec': '字节数发送/秒',
  'Packets Received/sec': '数据包接收/秒',
  'Packets Sent/sec': '数据包发送/秒',
  'Packets Received Discarded': '数据包接收丢弃',
  'Packets Outbound Discarded': '数据包发送丢弃',
  'Network Performance (Received)': '网络性能 (接收)',
  'Network Performance (Transmitted)': '网络性能 (发送)',
  'Network Performance': '网络性能',
  'Sent': '发送',
  'Received': '接收',
  'Network Packets': '网络数据包',
  'Packet Drops': '丢包',
  'Drop In': '删除进',
  'Drop Out': '删除出',
  'OS': 'OS',
  'OS Version': 'OS 版本',
  'Critical Disks': '危急',
  'Warning Disks': '需注意',
  'Normal Disks': '正常',
  'Insufficient Data Disks': '数据不足',
  'Insufficient Data': '数据不足',
  'Insufficient data': '数据不足',
  '# of Active VMs': '工作中虚拟机数量',
  'Memory': '内存',
  'Memory %': '内存 %',
  'Impact': '关系图',
  'event_layer.ALL': '全部',
  'event_layer.APP': '应用程序',
  'event_layer.VM': 'VM',
  'event_layer.DISK': '磁盘',
  'event_layer.HOST': '主机',
  'time_machine.event.detail': '{{description}} ({{eventLayer}}{{eventLevel}}) 在 {{datetime}}',
  'time_machine.play.done': '所有的事件关系图以展示完毕',
  'time_machine.event.search_bar.placeholder': '以事件名称、类别、等级或日期搜索事件列表',
  'time_machine.causality_event.probable_checkbox': '只显示最可能的根本事件',
  'time_machine.error.get_dropdown': '无法取得事件筛选条件。错误：{{message}}',
  'time_machine.error.get_timeline': '无法取得时间轴。错误：{{message}}',
  'time_machine.error.get_event_list': '无法取得事件列表。错误：{{ message }}',
  'time_machine.error.get_causality_event_list': '无法取得关联事件列表。错误：{{ message }}',
  'time_machine.error.get_event_impact': '无法取得关系图。错误：{{ message }}',
  'Past': '过去',
  'Future': '未来',
  'Physical Disks': '物理磁盘',
  'OS Disks': '虚拟磁盘',
  'Networks': '网络',
  'Performance': '性能',
  'Size': '容量',
  'Disk IO Usage': '磁盘 I/O 使用率',
  'Read': '读',
  'Write': '写',
  'Disk IO Requests': '磁盘 I/O 请求',
  'Read IO': '读取 I/O',
  'Write IO': '写入 I/O',
  'Disk IO Time': '磁盘 I/O 时间',
  'Read Time': '读取时间',
  'Write Time': '写入时间',
  'VM Name': '虚拟机名称',
  'Disk Read Latency': '磁盘读取延迟',
  'DiskProphet': '智能运维平台',
  'Federator.ai': '智能运维平台',
  'Unknown error occurred': '发生未知错误',
  'Log in to Continue': '登录以继续',
  'LOG IN': '登录',
  'Physical Servers': 'Linux 主机',
  'Host Group': '主机群组',
  'Disk Group': '磁盘群组',
  'Linux Host Capacity': '主机存储容量',
  'Host Capacity': '主机存储容量',
  'By OS/Platform': '按 OS/平台',
  'will fail out of': '个将故障,总数',
  'is predicted to fail': '个预测将故障',
  'By Media Type': '按介质类型',
  'Disk Failures': '故障预测',
  'More than 6 weeks': '大于6周',
  'Less than 6 weeks': '小于 6周',
  'Less than 2 weeks': '小于 2周',
  'Disks that provide no data': '磁盘未提供数据',
  'Disks that don\'t provide enough data for analysis': '磁盘未提供足够数据分析',
  'Linux Host Disk Performance': '主机存储性能',
  'Disk Throughput': '吞吐量',
  'Disk IO': 'I/O',
  'Disk Latency': '延迟',
  'Disk Failure Prediction v/s Actual': '故障预测 与 历史 对比',
  'Operating System': '操作系统',
  'Tags': '标签',
  'Show/Hide': '显示/隐藏',
  'Datastores': 'Datastores',
  'Hosts with no VMs': '无VM的主机',
  'Properties': '属性',
  'Zoom': '放大',
  'Zoom:': '放大',
  'Search item': '搜索',
  'CPU Utilization': 'CPU 利用率',
  'Memory Utilization': '内存利用率',
  'ESXi CPU Utilization': 'ESXi CPU 利用率',
  'ESXi Memory Utilization': 'ESXi 内存利用率',
  'VM CPU Utilization': 'VM CPU 利用率',
  'VM Memory Utilization': 'VM 内存利用率',
  'VM Received': 'VM 接收',
  'VM Transmitted': 'VM 发送',
  'ESXi Received': 'ESXi 接收',
  'ESXi Transmitted': 'ESXi 发送',
  'Host CPU': '主机 CPU',
  'Host Memory': '主机内存',
  'Host CPU Ready': '主机 CPU Ready',
  'Host Disk Read Throughput': '主机磁盘读取吞吐量',
  'Host Disk Write Throughput': '主机磁盘写入吞吐量',
  'Host Disk Read Latency': '主机磁盘读取延迟',
  'Host Disk Write Latency': '主机磁盘写入延迟',
  'Host Disk Read IO': '主机磁盘读取 I/O',
  'Host Disk Write IO': '主机磁盘写入 I/O',
  'Host Network Received': '主机网络接收',
  'Host Network Transmitted': '主机网络传输',
  'VMware CPU': 'VMware CPU',
  'VMware Memory': 'VMware 内存',
  'VMware Disk Read IO': 'VMware 磁盘读取 I/O',
  'VMware Disk Write IO': 'VMware 磁盘写入 I/O',
  'VMware Disk Read Throughput': 'VMware 磁盘读取吞吐量',
  'VMware Disk Write Throughput': 'VMware 磁盘写入吞吐量',
  'VMware Disk Read Latency': 'VMware 磁盘读取延迟',
  'VMware Disk Write Latency': 'VMware 磁盘写入延迟',
  'Network Drop In': '网络接收丢包',
  'Network Drop Out': '网络发送丢包',
  'CPU': 'CPU',
  'Memory Usage Percent': '内存数据包使用率',
  'VM CPU': 'VM CPU',
  'VM Memory': 'VM 内存',
  'VM Disk Read Latency': 'VM 磁盘读取延迟',
  'VM Disk Write Latency': 'VM 磁盘写入延迟',
  'VM Disk Read IO': 'VM 磁盘读取 I/O',
  'VM Disk Write IO': 'VM 磁盘写入 I/O',
  'VM Disk Read Throughput': 'VM 磁盘读取吞吐量',
  'VM Disk Write Throughput': 'VM 磁盘写入吞吐量',
  'Percent Memory Usage': '内存使用率',
  'Disk Used Megabytes': '磁盘已使用量',
  'Disk Read Throughput Persec': '磁盘读取 MBps',
  'Disk Write Throughput Persec': '磁盘写入 MBps',
  'Disk Read IO Persec': '磁盘读取 IOps',
  'Disk Write IO Persec': '磁盘写入 IOps',
  'Disk Read Latency Percent': '磁盘读取延迟百分比',
  'Disk Write Latency Percent': '磁盘写入延迟百分比',
  'Network Received Packet Persec': '网络每秒接收数据包',
  'Network Sent Packet Persec': '网络每秒发送数据包',
  'Network Error In': '网络错误接收',
  'Network Error Out': '网络错误发送',
  'Windows Version': 'Windows 版本',
  'Max CPU next 1 week': '未来一周 CPU 最大值',
  'Max Memory next 1 week': '未来一周内存最大值',
  'Max Load5 next 1 week': '未来一周 Load5 最大值',
  'Max CPU Ready next 1 week': '未来一周 CPU Ready 最大值',
  'Max CPU Next Week': '未来一周 CPU 最大值',
  'Max Memory Next Week': '未来一周内存最大值',
  'Max CPU Ready Next Week': '未来一周 CPU Ready 最大值',
  'Max Disk Read IO Next Week': '未来一周磁盘读取 I/O 最大值',
  'Max Disk Write IO Next Week': '未来一周磁盘写入 I/O 最大值',
  'Byte Used': '使用字节数 (Byte)',
  'RB Byte': '读取字节数 (Byte)',
  'Raw Byte Used': '原始使用字节数 (Byte)',
  'WR Byte': '写入字节数 (Byte)',
  'Server Type': '主机类型',
  'Save': '保存',
  'Cancel': '取消',
  'Edit Rule': '修改规则',
  'Add Rule': '添加规则',
  'Threshold is required.': '值是必填项',
  'Threshold should be a number.': '值应该是一个数字。',
  'Threshold should be positive.': '应该是一个正值.',
  'Threshold integer part should be less than 17 characters.': '值的整数部分应小于17个字符。',
  'Threshold float part should be less than 2 characters.': '值的小数部分应小于2个字符。',
  'Threshold for': '值的',
  'should be integer': '应为整数',
  'Current password': '当前密码',
  'New Password': '新密码',
  'Enter new password': '输入新密码',
  'Confirm New Password': '确认新密码',
  'Change': '更改',
  'Name': '主机名',
  'A valid password is required, minimum length of 4': '必须为最小长度是 4位的有效密码',
  'Retype new password': '重新输入新密码',
  'Password should match New Password': '密码应该与新密码一致',
  'Required': '必填',
  'Not changed, type to change password': '没有改变，输入更改密码',
  'Required, min 3 characters': '必填，最少3个字符',
  'Admin': '管理员',
  'ADMIN': '管理员',
  'Username': '用户名',
  'Password': '密码',
  'Retype Password': '重新输入密码',
  'Delete': '删除',
  'Next 1 day': '接下来的 1天',
  'Next 7 days': '接下来的 7天',
  'Next 14 days': '接下来的 14天',
  'Next 30 days': '接下来的 30天',
  'Next 90 days': '接下来的 90天',
  'Disk Read Bytes/sec': '磁盘读取字节数/秒',
  'Disk Write Bytes/sec': '磁盘写入字节数/秒',
  'Disk Reads/sec': '磁盘读取IOps (IOps)',
  'Disk Write/sec': '磁盘写入IOps (IOps)',
  '% Disk Read Time': '% 磁盘读取时间',
  '% Disk Write Time': '% 磁盘写入时间',
  'All host groups': '所有主机群组',
  'All disk groups': '所有磁盘群组',
  'Host': '主机',
  'Disk': '磁盘',
  'Delete User': '删除用户',
  'Are you sure to delete this user?': '你确认删除该用户？',
  'Ok': '确认',
  'User has been deleted': '用户已被删除',
  'Rule has been deleted': '规则已经被删除',
  'Password has been updated.': '密码已修改完成.',
  'Group has been updated.': '群组已更新完成.',
  'Group has been saved.': '群组已被保存.',
  'Group has been deleted': '群组已经被删除',
  'Are you sure to delete this rule?': '你确定要删除这个规则？',
  'Are you sure you want to delete the selected item??': '确实要删除所选项目吗？',
  'Delete Group': '删除群组',
  'Delete Rule': '删除规则',
  'Read Throughput': '读取吞吐量',
  'Write Throughput': '写入吞吐量',
  'Write Latency': '写入延迟',
  'Read Latency': '读取延迟',
  'Series': '系列',
  'Transmitted': '发送',
  '% User Time': '% 用户时间',
  '% Memory Usage': '% 内存使用率',
  'Disk Usage': '磁盘使用情况',
  'This panel is for simulating disk failure prediction.': '此功能用于模拟磁盘的故障预测结果。',
  "By tuning a disk's SMART data and performance from this panel,": '通过配置界面中的 SMART 信息和性能信息来模拟数据，',
  'DiskProphet will generate a new disk failure prediction from the tunning.': '软件会根据此模拟数据立刻生成一个新的故障预测结果。',
  'We call it "simulation" because the prediction is not generated': '之所以被称为“模拟”，是因为预测结果是从模拟器生成的数据得出的，',
  'from the actual data collected from a disk,rather from the tuning.': '而不是从实际硬盘中收集的。',
  'Please click the "Simulate" button when the configuration is done.': '模拟器配置完成后，请点击“模拟”按钮来生成预测结果。',
  'Click the "Restore" button to restore to the real prediction.': '如需恢复真实环境，请点击“恢复”按钮。',
  'If a simulation is not restored, it will be overwritten by the next prediction round.': '若环境未立刻恢复，也将在下一次真实预测产生时恢复。',
  'CPU/Memory': 'CPU/内存',
  'Disk Performance': '磁盘性能',
  'Is Simulated': '模拟数据',
  'In': '接收',
  'Out': '发送',
  'Zoom In': '放大',
  'Storage I/O': '存储 I/O',
  'Network': '网络',
  'Correlation': '关联性',
  'Utilization': '利用率',
  'VM Storage Latency': 'VM 存储延迟',
  'VM Storage Throughput': 'VM 存储吞吐量',
  'ESXi Storage Latency': 'ESXi 存储延迟',
  'ESXi Storage Throughput': 'ESXi 存储吞吐量',
  'Disks that will last more than 6 weeks': '磁盘将持续 6周以上',
  'Disks that will fail within 6 weeks': '在 6周内将故障的磁盘',
  'Disks that will fail within 2 weeks': '在 2周内将故障的磁盘',
  'General': '概括',
  'Uptime': '正常运行时间',
  'Notes': '记录',
  'Location': '位置',
  'Update Location': '更新位置',
  'Update Notes': '更新记录',
  'empty': '空',
  'Close': '关闭',
  'Select tags...': '选择标签',
  'Select': '选择',
  'Capacity Usage': '存储容量',
  'Description': '描述',
  'eg: Reserved Hosts': '例如：保留的主机',
  'Information about group': '关于群组的信息',
  'Fixed': '手动选择',
  'Smart': '智能匹配',
  'Parent Group': '父级群组',
  'Show only selected': '仅显示选定的',
  'Match': '匹配',
  'All Conditions': '所有条件',
  'Any Condition': '任意条件',
  'Conditions': '条件',
  'All Hosts': '所有主机',
  'Tag': '标签',
  'equal to': '等于',
  'not equal to': '不等于',
  'contains': '包含',
  'not contains': '不包含',
  'starts with': '开始',
  'ends with': '结束',
  'Field': '字段',
  'Operator': '操作',
  'Value': '值',
  'SMART': '智能匹配',
  'STATIC': '手动选择',
  'ALL': '所有条件',
  'ANY': '任一条件',
  'Cluster Name': '群集名称',
  'MONs': 'MONs',
  'Pools': 'Pools',
  'OSDs': 'OSDs',
  'OSD Used': '集群 OSD 使用字节数 (Byte)',
  'Max OSD Used next 1 week': '未来一周集群 OSD 使用字节数 (Byte) 最大值',
  'Cluster OSD Bytes Used %': '集群 OSD 使用字节数%',
  'Used Bytes': '使用字节数 (Byte)',
  'Raw Used Bytes': '原始使用字节数 (Byte)',
  'IO Bytes': 'I/O 字节数 (Byte)',
  'Read Bytes': '读取字节数 (Byte)',
  'Write Bytes': '写入字节数 (Byte)',
  'OP IO': 'I/O',
  'OP IO Latency': 'I/O 延迟 (秒)',
  'OP IO Bytes': 'I/O 字节数 (Byte)',
  'OP Read': '读取次数',
  'OP Write': '写入次数',
  'OP Read Latency': '读取延迟 (秒)',
  'OP Write Latency': '写入延迟 (秒)',
  'OP Read Out Bytes': '读取字节数 (秒)',
  'OP Write In Bytes': '写入字节数 (秒)',
  'Ceph Hosts': 'Ceph 主机',
  'Ceph Clusters': 'Ceph 集群',
  'Cluster': '集群',
  'Timeline': '时间轴',
  'NOW': 'NOW',
  'CUSTOM': 'CUSTOM',
  'Reduce duplicated event(s)': '去除重复事件',
  'Event Type Filter': '事件类别筛选',
  'Event Level Filter': '事件等级筛选',
  'Event Impact': '事件关系图',
  'Event List': '事件列表',
  'Event Name': '事件名称',
  'Causality Event List': '关联事件列表',
  'Email Settings': '邮箱设置',
  'Edit Email Settings': '修改邮箱设置',
  'Add Email Settings': '添加邮箱设置',
  'Delete Email Settings': '删除邮箱设置',
  'Subject': '主题',
  'Message': '内容',
  'ToEmail': '邮箱',
  'AppDynamic Event': 'APP 动态事件',
  'Subject is required.': '主题为必填项。',
  'Subject length should be less than 60 characters.': '主题长度应小于60个字符。',
  'Message length should be less than 1000 characters.': '内容长度应小于1000个字符。',
  'Email is required.': '邮箱为必填项。',
  'Email should be less than 60 characters.': '邮箱长度应小于60个字符。',
  'Email format is wrong.': '邮箱格式错误',
  'Description length should be less than 60 characters.': '描述长度应小于60个字符。',
  'There are some errors in email settings form': '电子邮箱设置表单中存在一些错误',
  'Are you sure to delete this email settings?': '您确定要删除此邮箱的设置吗？',
  'Cannot get email settings data. Error:': '无法获取邮箱的设置数据。 错误：{{ message }}',
  'Add email settings failed, Error: ': '添加邮箱设置失败，错误：',
  'Email settings has been deleted': '邮箱设置已被删除',
  'Please select a disk to simulate': '请选择一个磁盘来模拟',
  'Simulate successfully': '模拟成功',
  'Add rule failed': '添加规则失败',
  'There are some errors in add rule form': '添加规则表单中存在一些错误',
  'There are some errors in edit rule form': '修改规则表单中存在一些错误',
  'Language': '语言',
  'Network Error': '网络错误',
  'Error In': '错误进',
  'Error Out': '错误出',
  'Network Error (Error In)': '网络错误 (错误进)',
  'Network Error (Error Out)': '网络错误 (错误出)',
  'Group Name': '群组名',
  'kapacitor.smtp.service.port.note': '如果将port设置至465，将使用SSL / TLS连线; 如果port不为465但SMTP server支持STARTTLS，则使用STARTTLS连线; 其余情况则使用非加密连线。',
  'AllDisk': '所有磁盘',
  'AllHost': '所有主机',
  'No Data To Show': '无数据显示',
  'State': '状态',
  'true': '在线',
  'false': '离线'
}

export default {
  cn
}
