const en = {
  /** **************** menu ***********/
  // Dashboard
  'menu.dashboard': 'Dashboard',
  // Analytics
  'menu.ana': 'Analytics',
  'menu.ana.linux_hosts': 'Linux Hosts',
  'menu.ana.vmware_hosts': 'VMware Hosts',
  'menu.ana.vmware_vms': 'VMware VMs',
  'menu.ana.hypervisor': 'Hypervisor',
  'menu.ana.application': 'Application',
  'menu.ana.vm': 'VM',
  'menu.ana.physical_host': 'Physical Host',
  'menu.ana.infras': 'Infrastructure',
  'menu.ana.vmware_map': 'VMware Map',
  'menu.ana.nutanix_hosts': 'Nutanix Hosts',
  'menu.ana.nutanix_vms': 'Nutanix VMs',
  'menu.ana.windows_hosts': 'Windows Hosts',
  'menu.ana.ceph_hosts': 'Ceph Hosts',
  'menu.ana.ceph_clusters': 'Ceph Clusters',
  'menu.ana.applications': 'Applications',
  'menu.ana.server_summary': 'Server Summary',
  'menu.ana.physical_machines': 'Physical Machines',
  // Prediction
  'menu.pred': 'Prediction',
  'menu.pred.disk_failure': 'Disk Failure',
  'menu.pred.linux_hosts': 'Linux Hosts',
  'menu.pred.vmware_hosts': 'VMware Hosts',
  'menu.pred.vmware_vms': 'VMware VMs',
  'menu.pred.nutanix_hosts': 'Nutanix Hosts',
  'menu.pred.nutanix_vms': 'Nutanix VMs',
  'menu.pred.windows_hosts': 'Windows Hosts',
  'menu.pred.ceph_clusters': 'Ceph Clusters',
  // Groups
  'menu.grp': 'Groups',
  'menu.grp.host': 'Host Groups',
  'menu.grp.disk': 'Disk Groups',
  // Administration
  'menu.adm': 'Administration',
  'menu.adm.agents': 'Agents',
  'menu.adm.users': 'Users',
  'menu.adm.audit_log': 'Audit Log',
  'menu.adm.upload': 'Upload',
  'menu.adm.events': 'Events',
  'menu.adm.threshold': 'Alert Configuration',
  'menu.adm.email_settings': 'Email Notifications',
  'menu.adm.email_server_settings': 'Email Settings',
  'menu.adm.simulation': 'Disk Conditioner',
  'menu.adm.anomaly_dectect_config': 'Anomaly Detect Config',

  /** ***************Common*******************/
  'common.button.save': 'Save',
  'common.button.add': 'Add',
  'common.button.delete': 'Delete',
  'common.button.update': 'Update',
  'common.button.cancel': 'Cancel',
  'common.button.test': 'Test',
  'common.link.more': 'more',
  'common.link.less': 'less',

  'common.unit.second': 'Second(s)',

  'host_type.LINUX': 'Linux',
  'host_type.VMWARE': 'VMware',
  'host_type.NUTANIX': 'Nutanix',
  'host_type.WINDOWS': 'Windows',
  'host_type.CEPH': 'Ceph',
  'host_type.SAPHANA': 'SAP HANA',

  'common.column.critical_disk_count': 'Critical Disks',
  'common.column.warngin_disk_count': 'Warning Disks',
  'common.column.normal_disk_count': 'Normal Disks',
  'common.column.unknown_disk_count': 'Insufficient Data Disks',

  'common.disk.status.bad': 'Bad',
  'common.disk.status.good': 'Good',
  'common.disk.status.insufficient_data': 'Insufficient data',
  'common.disk.status.warning': 'Warning',

  'common.grid.footer.normal': 'Showing {{total}} entries',
  'common.grid.footer.show_reduce_count': '{{total}} of deduplicated events of {{unReduceTotal}} of total entries',

  /** ***************menu.ana.ceph_clusters*******************/
  'ceph_clusters.column.cluster': 'Cluster Name',
  'ceph_clusters.column.num_mon': 'MONs',
  'ceph_clusters.column.osds': 'OSDs',
  'ceph_clusters.column.mdss': 'MDSs',
  'ceph_clusters.column.num_pool': 'Pools',
  'ceph_clusters.column.osd_bytes_used_percentage': 'OSD Used',
  'ceph_clusters.column.health_status': 'Status',

  /** ***************menu.adm.agents*******************/
  'agent.column.cluster_name': 'Cluster Name',
  'agent.column.heartBeat_interval': 'HeartBeat Interval',
  'agent.column.host_ip_address': 'Host IP Address',
  'agent.column.host_name': 'Host Name',
  'agent.column.agent_version': 'Agent Version',
  'agent.column.last_update': 'Last Update',
  'agent.column.agent_status': 'Agent Status',
  'agent.column.agent_type': 'Agent Type',
  'agent.column.problems': 'Reason',

  'sai_agent.agent_typ.ceph': 'Ceph',
  'sai_agent.agent_typ.linux': 'Linux',
  'sai_agent.agent_typ.nutanix': 'Nutanix',
  'sai_agent.agent_typ.windows': 'Windows',
  'sai_agent.agent_typ.vmware': 'VMware',
  'sai_agent.agent_typ.appdynamics': 'AppDynamics',

  /** ***************E-Mail Settings*******************/
  'page.adm.email_settings': 'Email Notifications',
  'page.adm.email_settings.add': 'Add notification setting',
  'page.adm.email_settings.edit': 'Edit notification setting',
  'page.adm.email_settings.delete': 'Delete notification setting',

  'email_settings.email_type': 'Type',
  'email_settings.subject': 'Subject',
  'email_settings.message': 'Message',
  'email_settings.to': 'To',
  'email_settings.description': 'description',

  'email_settings.note': 'Set up the specific system event/log type to the specific members.',
  'email_settings.subject.note': 'The email subject related to the type of email that may include the system arguments direct to the type. You can edit the default subject if necessary.',
  'email_settings.message.note': 'The email message related to the type of email that include the system arguments as necessary information for depicting this email notification. You can edit the default message if necessary.',
  'email_settings.to.note': 'Enter the email accounts of those who should receive this notification. Separated by semicolon.',
  'email_settings.description.note': 'A note for this email notification setting',

  'email_settings.to.placeholder': 'email1;email2;email3...',

  'validation.email_settings.subject.obligate': 'Subject is required.',
  'validation.email_settings.subject.length': 'Subject length should be less than 1024 characters',
  'validation.email_settings.message.length': 'Message length should be less than 4096 characters.',
  'validation.email_settings.description.length': 'Description length should be less than 1024 characters.',
  'validation.email_settings.to.obligate': 'To email is required.',
  'validation.email_settings.to.length': 'To email should be less than 512 characters.',
  'validation.email_settings.from.obligate': 'From email is required.',
  'validation.email_settings.from.length': 'From email should be less than 60 characters.',
  'validation.email_settings.fail': 'There are some errors in email settings form.',
  'validation.email_settings.email.invalid.format': 'Email format is wrong.',

  'email_settings.delete.confirm': 'Are you sure to delete this email settings?',
  'email_settings.delete.success': 'Email settings has been deleted.',
  'email_settings.delete.fail.appendErrMsg': 'Delete email settings failed, Error: {{ message }}',
  'email_settings.add.fail.appendErrMsg': 'Add email settings failed, Error: {{ message }}',
  'email_settings.edit.fail.appendErrMsg': 'Edit email settings failed, Error: {{ message }}',
  'email_settings.get.fail.appendErrMsg': 'Cannot get email settings data. Error: {{ message }}',

  'email_type.METRICS_MONITORING': 'Metrics Monitoring',
  'email_type.METRICS_MONITORING.note': 'Alerts that violate workload thresholds',
  'email_type.APPDYNAMICS_EVENT': 'AppDynamics Event',
  'email_type.APPDYNAMICS_EVENT.note': 'Events that violate AppDynamics Health Rules',
  'email_type.DISK_PREDICTION': 'Disk Prediction',
  'email_type.DISK_PREDICTION.note': 'Disk prediction state that shows "Bad"',
  'email_type.LICENSE': 'License',
  'email_type.LICENSE.note': 'A reminder of license expiration',
  'email_type.ANOMALY_LOG': 'Anomaly Log',
  'email_type.ANOMALY_LOG.note': 'Anomaly detection via log analysis',
  'email_type.ANOMALY_METRICS': 'Anomaly Metric',
  'email_type.ANOMALY_METRICS.note': 'Anomaly detection via metric analysis',
  // 'email_type.SMTP_TEST': ,
  // 'email_type.SMTP_TEST.note': ,

  /** ***************E-Mail SMTP Server Settings*******************/
  'page.adm.email_server_settings': 'Email Settings',

  'email_server_settings.general_settings': 'General Settings',
  'email_server_settings.server_settings': 'Email Server Settings',
  'email_server_settings.default_send_to': 'Default Email Receivers',
  'email_server_settings.from': 'From',
  'email_server_settings.smtp_host': 'SMTP Host',
  'email_server_settings.smtp_port': 'SMTP Port',
  'email_server_settings.authenticationRequired': 'Authentication Required',
  'email_server_settings.smtp_username': 'SMTP Username',
  'email_server_settings.smtp_password': 'SMTP Password',
  'email_server_settings.smtp_confirm_password': 'Confirm SMTP Password',
  'email_server_settings.enabled': 'Enabled',
  'email_server_settings.try_to_connect_smtp_server': 'Try To Connect SMTP Server',
  'email_server_settings.save_and_send_test_email': 'Save And Send Test Email',
  'email_server_settings.try_to_connect_smtp_server.successfully': 'Test connection successfully, if SMTP setting is valid, you will receive testing mail.',
  'email_server_settings.save_and_send_test_email.successfully': 'Save successfully, if SMTP setting is valid, you will receive testing mail.',

  'validation.email_server_settings.smtp_host.obligate': 'Host is required.',
  'validation.email_server_settings.smtp_host.length': 'Host length should be less than 200 characters.',
  'validation.email_server_settings.smtp_port.obligate': 'Port is required.',
  'validation.email_server_settings.smtp_port.data_type': 'Port should be number type (0 ~ 65535)',
  'validation.email_server_settings.smtp_port.range': 'Port should be 0 ~ 65535',
  'validation.email_server_settings.smtp_username.length': 'SMTP username length should be less than 200 characters.',
  'validation.email_server_settings.smtp_password.length': 'SMTP password length should be less than 200 characters.',
  'validation.email_server_settings.smtp_confirm_password_not_equal': 'SMTP confirm password should equal SMTP password.',

  /** ***************Events*******************/
  'event_type.ALL': 'All',
  'event_type.FIRST_AGENT_HEARTBEAT': 'First Agent Heartbeat',
  'event_type.INTERVAL_AGENT_HEARTBEAT': 'Interval Agent Heartbeat',
  'event_type.METRICS_MONITORING': 'Metrics Monitoring',
  'event_type.MONITORING': 'Metrics Alert',
  'event_type.AGENT_MONITORING': 'Agent Monitoring',
  'event_type.DISK_FAILURE_PREDICTION': 'Disk Failure Prediction',
  'event_type.LICENSE': 'License',
  'event_type.ANOMALY_METRICS': 'Anomaly Metric',
  'event_type.APPDYNAMICS_EVENT': 'AppDynamics Event',
  'event_type.DISKPROPHET': 'DiskProphet',
  'event_type.ANOMALY_LOG': 'Anomaly Log',

  'sai_event.event_type.First Agent Heartbeat': 'First Agent Heartbeat',
  'sai_event.event_type.Interval Agent Heartbeat': 'Interval Agent Heartbeat',
  'sai_event.event_type.Metrics Monitoring': 'Metrics Monitoring',
  'sai_event.event_type.Metrics Alert': 'Metrics Alert',
  'sai_event.event_type.Agent Monitoring': 'Agent Monitoring',
  'sai_event.event_type.Disk Failure Prediction': 'Disk Failure Prediction',
  'sai_event.event_type.License': 'License',
  'sai_event.event_type.Anomaly Metric': 'Anomaly Metric',
  'sai_event.event_type.AppDynamics Event': 'AppDynamics Event',
  'sai_event.event_type.DiskProphet': 'DiskProphet',
  'sai_event.event_type.Anomaly Log': 'Anomaly Log',

  'event_level.ALL': 'All',
  'event_level.DEBUG': 'Debug',
  'event_level.INFO': 'Info',
  'event_level.WARN': 'Warning',
  'event_level.ERROR': 'Error',
  'event_level.FATAL': 'Fatal',

  'sai_event.event_level.Debug': 'Debug',
  'sai_event.event_level.Info': 'Info',
  'sai_event.event_level.Warn': 'Warning',
  'sai_event.event_level.Error': 'Error',
  'sai_event.event_level.Fatal': 'Fatal',

  /** ***************Workload*******************/
  'workload.DISKIO_READ_BYTES': 'Disk Read Throughput',
  'workload.DISKIO_WRITE_BYTES': 'Disk Write Throughput',
  'workload.DISKID_READS': 'Disk Read IO',
  'workload.DISKIO_WRITES': 'Disk Write IO',
  'workload.DISKIO_READ_TIME': 'Disk Read Latency',
  'workload.DISKIO_WRITE_TIME': 'Disk Write Latency',
  'workload.NET_BYTES_RECV': 'Network Received Usage',
  'workload.NET_BYTES_SENT': 'Network Sent Usage',
  'workload.NET_PACKETS_RECV': 'Network Received Packet',
  'workload.NET_PACKETS_SENT': 'Network Sent Packet',
  'workload.NET_DROP_IN': 'Network Drop In',
  'workload.NET_DROP_OUT': 'Network Drop Out',
  'workload.NET_ERROR_IN': 'Network Error In',
  'workload.NET_ERROR_OUT': 'Network Error Out',
  'workload.CPU_USAGE_USER': 'CPU',
  'workload.MEM_USED_PERCENT': 'Memory Used Percent',
  'workload.MEM_USED': 'Memory Used',
  'workload.SYSTEM_LOAD5': 'Load5',
  'workload.DISK_USED': 'Capacity',

  'workload.HOSTSYSTEM_CPU_USAGE_AVERAGE': 'Host CPU',
  'workload.HOSTSYSTEM_MEM_USAGE_AVERAGE': 'Host Memory',
  'workload.HOSTSYSTEM_DISK_READ_AVERAGE': 'Host Disk Read Throughput',
  'workload.HOSTSYSTEM_DISK_WRITE_AVERAGE': 'Host Disk Write Throughput',
  'workload.HOSTSYSTEM_DATASTORE_TOTALREADLATENCY_AVERAGE': 'Host Disk Read Latency',
  'workload.HOSTSYSTEM_DATASTORE_TOTALWRITEDLATENCY_AVERAGE': 'Host Disk Write Latency',
  'workload.HOSTSYSTEM_DATASTORE_NUMBERREADAVERAGED_AVERAGE': 'Host Disk Read IO',
  'workload.HOSTSYSTEM_DATASTORE_NUMBERWRITEAVERAGED_AVERAGE': 'Host Disk Write IO',
  'workload.HOSTSYSTEM_NET_RECEIVED_AVERAGE': 'Host Network Received',
  'workload.HOSTSYSTEM_NET_TRANSMITTED_AVERAGE': 'Host Network Transmitted',
  'workload.HOSTSYSTEM_NET_ERROR_IN': 'Host Network Error In',
  'workload.HOSTSYSTEM_NET_ERROR_OUT': 'Host Network Error Out',
  'workload.VIRTUALMACHINE_CPU_USAGE_AVERAGE': 'VM CPU',
  'workload.VIRTUALMACHINE_MEM_USAGE_AVERAGE': 'VM Memory',
  'workload.VIRTUALMACHINE_DATASTORE_NUMBERREADAVERAGED_AVERAGE': 'VM Disk Read IO',
  'workload.VIRTUALMACHINE_DATASTORE_NUMBERWRITEAVERAGED_AVERAGE': 'VM Disk Write IO',
  'workload.VIRTUALMACHINE_DATASTORE_READ_AVERAGE': 'VM Disk Read Throughput',
  'workload.VIRTUALMACHINE_DATASTORE_WRITE_AVERAGE': 'VM Disk Write Throughput',
  'workload.VIRTUALMACHINE_DATASTORE_TOTALREADLATENCY_AVERAGE': 'VM Disk Read Latency',
  'workload.VIRTUALMACHINE_DATASTORE_TOTALWRITELATENCY_AVERAGE': 'VM Disk Write Latency',
  'workload.VIRTUALMACHINE_NETWORK_RECEIVED_AVERAGE': 'VM Network Reveiced Average',
  'workload.VIRTUALMACHINE_NETWORK_TRANSMITTED_AVERAGE': 'VM Network Transmitted Average',
  'workload.VIRTUALMACHINE_NETWORK_PACKETSRX_SUMMATION': 'VM Network Received Packet',
  'workload.VIRTUALMACHINE_NETWORK_PACKETSTX_SUMMATION': 'VM Network Transmitted Packet',

  'workload.NUTANIX_DISKIO_READ_BYTES': 'Disk Read Throughput',
  'workload.NUTANIX_DISKIO_WRITE_BYTES': 'Disk Write Throughput',
  'workload.NUTANIX_DISKIO_READS': 'Disk Read IO',
  'workload.NUTANIX_DISKIO_WRITES': 'Disk Write IO',
  'workload.NUTANIX_DISKIO_READ_TIME': 'Disk Read Latency',
  'workload.NUTANIX_DISKIO_WRITE_TIME': 'Disk Write Latency',
  'workload.NUTANIX_NET_BYTES_RECV': 'Network Received Usage',
  'workload.NUTANIX_NET_BYTES_SENT': 'Network Sent Usage',
  'workload.NUTANIX_NET_PACKETS_RECV': 'Network Received Packet',
  'workload.NUTANIX_NET_PACKETS_SENT': 'Network Sent Packet',
  'workload.NUTANIX_NET_DROP_IN': 'Network Drop In',
  'workload.NUTANIX_NET_DROP_OUT': 'Network Drop Out',
  'workload.NUTANIX_NET_ERROR_IN': 'Network Error In',
  'workload.NUTANIX_NET_ERROR_OUT': 'Network Error Out',
  'workload.NUTANIX_CPU_USAGE_USER': 'CPU',
  'workload.NUTANIX_MEM_USAGE_PERCENT': 'Memory Usage Percent',
  'workload.NUTANIX_SYSTEM_LOAD5': 'Load5',
  'workload.NUTANIX_VIRTUALMACHINE_CPU_USAGE_PPM': 'VM CPU',
  'workload.NUTANIX_VIRTUALMACHINE_GEST_MEM_USAGE_PPM': 'VM Memory',
  'workload.NUTANIX_VIRTUALMACHINE_DISKIO_READ_TIME': 'VM Disk Read Latency',
  'workload.NUTANIX_VIRTUALMACHINE_DISKIO_WRITE_TIME': 'VM Disk Write Latency',
  'workload.NUTANIX_VIRTUALMACHINE_DISKIO_READ': 'VM Disk Read IO',
  'workload.NUTANIX_VIRTUALMACHINE_DISK_WRITE': 'VM Disk Write IO',
  'workload.NUTANIX_VIRTUALMACHINE_DISK_READ_THROUGHPUT': 'VM Disk Read Throughput',
  'workload.NUTANIX_VIRTUALMACHINE_DISK_WRITE_THROUGHPUT': 'VM Disk Write Throughput',

  'workload.WIN_CPU_PERCENT_USER_TIME': 'CPU',
  'workload.WIN_MEM_PERCENT_MEMORY_USAGE': 'Percent Memory Usage',
  'workload.WIN_DISK_USED_MEGABYTES': 'Capacity Megabytes',
  'workload.WIN_DISKIO_READ_BYTES_PERSEC': 'Disk Read Throughput Persec',
  'workload.WIN_DISKIO_WRITE_BYTES_PERSEC': 'Disk Write Throughput Persec',
  'workload.WIN_DISKIO_READS_PERSEC': 'Disk Read IO Persec',
  'workload.WIN_DISKIO_WRITES_PERSEC': 'Disk Write IO Persec',
  'workload.WIN_DISKIO_PERCENT_DISK_READ_TIME': 'Disk Read Latency Percent',
  'workload.WIN_DISKIO_PERCENT_DISK_WRITE_TIME': 'Disk Write Latency Percent',
  'workload.WIN_NET_PACKETS_RECV_PERSEC': 'Network Received Packet Persec',
  'workload.WIN_NET_PACKETS_SENT_PERSEC': 'Network Sent Packet Persec',
  'workload.WIN_NET_BYTES_RECV_PERSEC': 'Network Received Usage',
  'workload.WIN_NET_BYTES_SENT_PERSEC': 'Network Sent Usage',
  'workload.WIN_NET_PACKETS_DROP_IN': 'Network Drop In',
  'workload.WIN_NET_PACKETS_DROP_OUT': 'Network Drop Out',
  'workload.WIN_NET_PACKETS_ERROR_IN': 'Network Error In',
  'workload.WIN_NET_PACKETS_ERROR_OUT': 'Network Error Out',

  'workload.CEPH_CLUSTER_OSD_BYTES_USED_PERCENTAGE': 'Cluster OSD Bytes Used Percentage',
  'workload.CEPH_POOL_BYTES_USED': 'Pool Used Bytes',
  'workload.CEPH_POOL_RAW_BYTES_USED': 'Pool Raw Used Bytes',
  'workload.CEPH_POOL_READ_BYTES': 'Pool Read IO Bytes',
  'workload.CEPH_POOL_WRITE_BYTES': 'Pool Write IO Bytes',
  'workload.CEPH_OSD_READS': 'OSD OP IO Read',
  'workload.CEPH_OSD_WRITES': 'OSD OP IO Write',
  'workload.CEPH_OSD_READ_TIME': 'OSD OP IO Read Latency',
  'workload.CEPH_OSD_WRITE_TIME': 'OSD OP IO Write Latency',
  'workload.CEPH_OSD_READ_OUT_BYTES': 'OSD OP IO Read Out',
  'workload.CEPH_OSD_WRITE_IN_BYTES': 'OSD OP IO Write In',
  'workload.CEPH_OSD_STAT_BYTES_USED_PERCENTAGE': 'OSD Used Byte Percentage',

  /** ***************Disk Failure*******************/
  'diskfailure.grid.not_support_host_type': 'This host type is not supported now. Can not redirect to the host page.',

  /** ***************Analytics > Applications*******************/
  'analytics.applications.grid.applications_name': 'Application Name',
  'analytics.applications.grid.host': 'Host',
  'analytics.applications.grid.host_ip': 'Host IP',
  'analytics.applications.event.grid.name': 'Name',
  'analytics.applications.event.grid.level': 'Level',
  'analytics.applications.event.grid.start_time': 'Start Time',
  'analytics.applications.event.grid.end_time': 'End Time',

  'First Agent Heartbeat': 'First Agent Heartbeat',
  'Interval Agent Heartbeat': 'Interval Agent Heartbeat',
  'Metrics Monitoring': 'Metrics Monitoring',
  'Metrics Alert': 'Metrics Alert',
  'Agent Monitoring': 'Agent Monitoring',
  'Disk Failure Prediction': 'Disk Failure Prediction',
  'Disk Health Prediction': 'Disk Health Prediction',

  'Debug': 'Debug',
  'Info': 'Info',
  'Warn': 'Warning',
  'Error': 'Error',
  'Fatal': 'Critical',

  // Dashboard
  'Dashboard': 'Dashboard',
  // Analytics
  'Analytics': 'Analytics',
  'Linux Hosts': 'Linux Hosts',
  'VMware Hosts': 'VMware Hosts',
  'VMware VMs': 'VMware VMs',
  'VMware Map': 'VMware Map',
  'Nutanix Hosts': 'Nutanix Hosts',
  'Nutanix VMs': 'Nutanix VMs',
  'Windows Hosts': 'Windows Hosts',
  'Server Summary': 'Server Summary',
  'Time Machine': 'Time Machine',

  // Prediction
  'Prediction': 'Prediction',
  'Disk Failure': 'Disk Failure',
  // Groups
  'Groups': 'Groups',
  'Group': 'Group',
  'Host Groups': 'Host Groups',
  'Disk Groups': 'Disk Groups',
  // Administration
  'Administration': 'Administration',
  'Agents': 'Agents',
  'Users': 'Users',
  'Audit Log': 'Audit Log',
  'Upload': 'Upload',
  'Events': 'Events',
  'Alert Configuration': 'Alert Configuration',
  'Disk Conditioner': 'Disk Conditioner',

  'Summary': 'DiskProphet Summary',
  'Agent Status': 'Agent Status',
  'Disks': 'Disks',
  'Monitored Disk Space': 'Monitored Disk Space',
  'Critical': 'Critical',
  'Warning': 'Warning',
  'Normal': 'Normal',

  // Anomaly Configuration
  'Anomaly.SubTitle': 'Anomaly Configuration',
  'Anomaly.selectHost': 'Select host',
  'Anomaly.Category': 'Category',
  'Anomaly.Enable': 'Enable',
  'Anomaly.Sensitivity': 'Sensitivity',
  'Anomaly.SN': 'SN',
  'Anomaly.OSType': 'OS Type',
  'trueEnable': 'true',
  'falseEnable': 'false',
  'Low': 'Low',
  'Medium': 'Medium',
  'High': 'High',
  'Anomaly.Search': "Please search and check the host(s) you'd like to detect",
  'Anomaly.LoadFaild': 'Load Faild:',
  'Anomaly.hostLoadFaild': 'Host Load Faild:',
  'Anomaly.deleted': 'Anomaly Configuration has been deleted',
  'Anomaly.delete.Config': 'Delete Anomaly Configuration',
  'Anomaly.sure.delete': 'Are you sure to delete it?',
  'Anomaly.Add.successfully': 'Add successfully',
  'Anomaly.Save.success': 'Save success',
  'LINUX': 'Linux',
  'VMWARE': 'VMware',
  'NUTANIX': 'Nutanix',
  'CEPH': 'Ceph',
  'WINDOWS': 'Windows',
  'LINUX_CPU': 'Linux CPU',
  'LINUX_CAPACITY': 'Linux Capacity',
  'LINUX_DISK_PERFORMANCE': 'Linux Disk Performance',
  'LINUX_MEMORY': 'Linux Memory',
  'LINUX_NETWORKS': 'Linux Networks',
  'LINUX_LOAD': 'Linux Load',
  'VMWARE_HOST_CPU': 'VMware Host CPU',
  'VMWARE_HOST_MEMORY': 'VMware Host Memory',
  'VMWARE_HOST_NETWORKS': 'VMware Host Networks',
  'VMWARE_HOST_DISK_PERFORMANCE': 'VMware Host Disk Performance',
  'VMWARE_VM_CPU': 'VMware VM CPU',
  'VMWARE_VM_MEMORY': 'VMware VM Memory',
  'VMWARE_VM_DISK_PERFORMANCE': 'VMware VM Disk Performance',
  'VMWARE_VM_NETWORKS': 'VMware VM Networks',
  'NTNX_VM_CPU': 'Ntnx VM CPU',
  'NTNX_VM_DISK_PERFORMANCE': 'Ntnx VM Disk Performance',
  'NTNX_VM_MEMORY': 'Ntnx VM Memory',
  'NTNX_HOST_CPU': 'Ntnx Host CPU',
  'NTNX_HOST_CAPACITY': 'Ntnx Host Capacity',
  'NTNX_HOST_DISK_PERFORMANCE': 'Ntnx Host Disk Performance',
  'NTNX_HOST_MEMORY': 'Ntnx Host Memory',
  'NTNX_HOST_NETWORKS': 'Ntnx Host Networks',
  'NTNX_HOST_LOAD': 'Ntnx Host Load',
  'CEPH_OSD': 'Ceph OSD',
  'CEPH_POOL': 'Ceph Pool',
  'WINDOWS_CPU': 'Windows CPU',
  'WINDOWS_CAPACITY': 'Windows Capacity',
  'WINDOWS_DISK_PERFORMANCE': 'Windows Disk Performance',
  'WINDOWS_MEMORY': 'Windows Memory',
  'WINDOWS_NETWORKS': 'Windows Networks',
  // ===========

  'Save/Reset Layout': 'Save/Reset Layout',
  'Save Layout': 'Save Layout',
  'Reset to Default': 'Reset to Default',
  'Arrange': 'Arrange',
  'Export to PDF': 'Export to PDF',
  'Export to CSV': 'Export to CSV',
  'Filter': 'Filter',
  'Search for...': 'Search for...',
  'Count': 'Count',
  'System': 'System',
  'User': 'User',
  'Used': 'Used',
  'Cached': 'Cached',
  'Free': 'Free',
  'Load5': 'Load5',
  'ESX Memory': 'ESX Memory',
  'CPU Ready': 'CPU Ready',
  'Failure Prediction': 'Failure Prediction',
  'Health Prediction': 'Health Prediction',
  'Needs Attention': 'Needs Attention',
  'Unknown': 'Unknown',
  'Good': 'Good',
  'Bad': 'Bad',
  'Loaded server count / Total server count': 'Loaded server count / Total server count',
  'Disk Health': 'Disk Health',
  'Total Disks': 'Total Disks',
  'Search by name': 'Search by name',
  'Actual': 'Actual',
  'Historical': 'Historical',
  'VMware Version': 'VMware Version',
  'ESX Host': 'ESX Host',
  'Datastore': 'Datastore',
  'Predicted': 'Predicted',
  'Weeks': 'Weeks',
  'Actions': 'Actions',
  'alert_config_action_email_description': 'Select this option to enable email alert sent to the Default email receivers (set up default email receivers on the Email Settings page)',
  'alert_config_action_email_error': 'The default email receiver(s) is empty. Please go to the Email Settings page to set up the default email receiver(s)',
  'alert_config_rule_description': 'Metric that violates this rule will trigger an event alert',
  'From': 'From',
  'To': 'To',
  'From Date': 'From Date',
  'To Date': 'To Date',
  'From Time': 'From Time',
  'To Time': 'To Time',
  'Search': 'Search',
  'Refresh': 'Refresh',
  'All': 'All',
  'Log In': 'Log In',
  'Log Out': 'Log Out',
  'Change Password': 'Change Password',
  'Changed Password': 'Changed Password',
  'IP Address': 'IP Address',
  'Action': 'Action',
  'Date': 'Date',
  'Status': 'Status',
  'Reduce duplicated event(s)': 'Reduce duplicated event(s)',
  'Event Type Filter': 'Event Type Filter',
  'Event Level Filter': 'Event Level Filter',
  'Event Impact': 'Event Impact',
  'event_layer.ALL': 'All',
  'event_layer.APP': 'App',
  'event_layer.VM': 'VM',
  'event_layer.DISK': 'Disk',
  'event_layer.HOST': 'Host',
  'time_machine.event.detail': '{{description}} ({{eventLayer}} {{eventLevel}}) by {{datetime}}',
  'time_machine.play.done': 'All event impact have played',
  'time_machine.event.search_bar.placeholder': 'Search Event List by Event Name, Type, Level or Date',
  'time_machine.causality_event.probable_checkbox': 'The most probable causality events only',
  'time_machine.error.get_dropdown': 'Failed to get event filter, Error: {{message}}',
  'time_machine.error.get_timeline': 'Failed to get timeline, Error: {{message}}',
  'time_machine.error.get_event_list': 'Failed to get event list, Error: {{message}}',
  'time_machine.error.get_causality_event_list': 'Failed to get causality event list, Error: {{message}}',
  'time_machine.error.get_event_impact': 'Failed to get event impact, Error: {{message}}',
  'Past': 'Past',
  'Future': 'Future',
  'Title': 'Title',
  'Agent Host': 'Agent Host',
  'Host IP': 'Host IP',
  'Type': 'Type',
  'Level': 'Level',
  'There is no more event in this time range': 'There is no more event in this time range',
  'Event counts:': 'Event counts:',
  'Drive Name': 'Drive Name',
  'Host Name': 'Host Name',
  'Confidence': 'Confidence',
  'Time of Prediction': 'Time of Prediction',
  'Symptom': 'Symptom',
  'Recommended Replacement Time': 'Recommended Replacement Time',
  'Serial #': 'Serial #',
  'Disk Vendor': 'Disk Vendor',
  'Model': 'Model',
  'Temperature': 'Temperature',
  'Event Type': 'Event Type',
  'Sector Error Count': 'Sector Error Count',
  'Max': 'Max',
  'None': 'None',
  'Error Correction Count': 'Error Correction Count',
  'HW Instability (a collection of disk hardware related attributes, such as G-sense error rate, high fly writes, etc.)': 'HW Instability (a collection of disk hardware related attributes, such as G-sense error rate, high fly writes, etc.)',
  'Historic Average Workload IO': 'Historic Average Workload IO',
  'Historic Average Workload Memory': 'Historic Average Workload Memory',
  'Simulate': 'Simulate',
  'Restore': 'Restore',
  'processing': 'processing',
  'Host Type': 'Host Type',
  'Metrics': 'Metrics',
  'Operand ': 'Operand ',
  'Default action is event': 'Default action is event',
  'Note': 'Note',
  'Threshold': 'Threshold',
  'Disk Read Throughput': 'Disk Read Throughput',
  'Disk Write Throughput': 'Disk Write Throughput',
  'Disk Read IO': 'Disk Read IO',
  'Disk Write IO': 'Disk Write IO',
  'Disk Read Latency': 'Disk Read Latency',
  'Disk Write Latency': 'Disk Write Latency',
  'Network Received Usage': 'Network Received Usage',
  'Network Sent Usage': 'Network Sent Usage',
  'Network Received Packet': 'Network Received Packet',
  'Network Sent Packet': 'Network Sent Packet',
  'Network Drop in': 'Network Drop in',
  'Network Drop out': 'Network Drop out',
  'Memory Used Percent': 'Memory Used Percent',
  'Memory Used': 'Memory Used',
  'Capacity': 'Capacity',
  'Unit': 'Unit',
  'Add': 'Add',
  'Upload a file with .7z extenstion': 'Upload a file with .7z extenstion',
  'Please choose a .7z file to upload': 'Please choose a .7z file to upload',
  'Uploading': 'Uploading',
  'Upload successfully': 'Upload successfully',
  'Upload failed': 'Upload failed',
  'Edit': 'Edit',
  'Role': 'Role',
  'First Name': 'First Name',
  'Last Name': 'Last Name',
  'Email': 'Email',
  'Phone': 'Phone',
  'Agent Domain Id': 'Agent Domain Id',
  'Cluster Domain Id': 'Cluster Domain Id',
  'HeartBeat Interval': 'HeartBeat Interval',
  'Host IP Address': 'Host IP Address',
  'Agent Version': 'Agent Version',
  'Last Update': 'Last Update',
  'Last 1 hour': 'Last 1 hour',
  'Last 12 hours': 'Last 12 hours',
  'Last 1 day': 'Last 1 day',
  'Last 7 days': 'Last 7 days',
  'Last 30 days': 'Last 30 days',
  'Network Usage': 'Network Usage',
  'Network Usage (Received)': 'Network Usage (Received)',
  'Network Usage (Sent)': 'Network Usage (Sent)',
  'Network Packets (Received)': 'Network Packets (Received)',
  'Network Packets (Sent)': 'Network Packets (Sent)',
  'Packet Drops (Drop In)': 'Packet Drops (Drop In)',
  'Packet Drops (Drop Out)': 'Packet Drops (Drop Out)',
  'Bytes Received/sec': 'Bytes Received/sec',
  'Bytes Sent/sec': 'Bytes Sent/sec',
  'Packets Received/sec': 'Packets Received/sec',
  'Packets Sent/sec': 'Packets Sent/sec',
  'Packets Received Discarded': 'Packets Received Discarded',
  'Packets Outbound Discarded': 'Packets Outbound Discarded',
  'Network Performance (Received)': 'Network Performance (Received)',
  'Network Performance (Transmitted)': 'Network Performance (Transmitted)',
  'Network Performance': 'Network Performance',
  'Sent': 'Sent',
  'Received': 'Received',
  'Network Packets': 'Network Packets',
  'Packet Drops': 'Packet Drops',
  'Drop In': 'Drop In',
  'Drop Out': 'Drop Out',
  'OS': 'OS',
  'OS Version': 'OS Version',
  'Critical Disks': 'Critical Disks',
  'Warning Disks': 'Warning Disks',
  'Normal Disks': 'Normal Disks',
  'Insufficient Data Disks': 'Insufficient Data Disks',
  'Insufficient Data': 'Insufficient Data',
  'Insufficient data': 'Insufficient data',
  '# of Active VMs': '# of Active VMs',
  'Memory': 'Memory',
  'Memory %': 'Memory %',
  'Impact': 'Impact',
  'Physical Disks': 'Physical Disks',
  'OS Disks': 'OS Disks',
  'Networks': 'Networks',
  'Performance': 'Performance',
  'Size': 'Size',
  'Disk IO Usage': 'Disk IO Usage',
  'Read': 'Read',
  'Write': 'Write',
  'Disk IO Requests': 'Disk IO Requests',
  'Read IO': 'Read IO',
  'Write IO': 'Write IO',
  'Disk IO Time': 'Disk IO Time',
  'Read Time': 'Read Time',
  'Write Time': 'Write Time',
  'VM Name': 'VM Name',
  'DiskProphet': 'DiskProphet',
  'Federator.ai': 'Federator.ai',
  'Unknown error occurred': 'Unknown error occurred',
  'Log in to Continue': 'Log in to Continue',
  'LOG IN': 'LOG IN',
  'Physical Servers': 'Physical Servers',
  'Host Group': 'Host Group',
  'Disk Group': 'Disk Group',
  'Linux Host Capacity': 'Linux Host Capacity',
  'Host Capacity': 'Host Capacity',
  'By OS/Platform': 'By OS/Platform',
  'will fail out of': 'will fail out of',
  'is predicted to fail': 'is predicted to fail',
  'By Media Type': 'By Media Type',
  'Disk Failures': 'Disk Failures',
  'More than 6 weeks': 'More than 6 weeks',
  'Less than 6 weeks': 'Less than 6 weeks',
  'Less than 2 weeks': 'Less than 2 weeks',
  'Disks that provide no data': 'Disks that provide no data',
  'Disks that don\'t provide enough data for analysis': 'Disks that don\'t provide enough data for analysis',
  'Linux Host Disk Performance': 'Linux Host Disk Performance',
  'Disk Throughput': 'Disk Throughput',
  'Disk IO': 'Disk IO',
  'Disk Latency': 'Disk Latency',
  'Disk Failure Prediction v/s Historical': 'Disk Failure Prediction v/s Historical',
  'Operating System': 'Operating System',
  'Tags': 'Tags',
  'Show/Hide': 'Show/Hide',
  'Datastores': 'Datastores',
  'Hosts with no VMs': 'Hosts with no VMs',
  'Properties': 'Properties',
  'Zoom': 'Zoom',
  'Zoom:': 'Zoom:',
  'Search item': 'Search item',
  'CPU Utilization': 'CPU Utilization',
  'Memory Utilization': 'Memory Utilization',
  'ESXi CPU Utilization': 'ESXi CPU Utilization',
  'ESXi Memory Utilization': 'ESXi Memory Utilization',
  'VM CPU Utilization': 'VM CPU Utilization',
  'VM Memory Utilization': 'VM Memory Utilization',
  'VM Recived': 'VM Recived',
  'VM Transmitted': 'VM Transmitted',
  'ESXi Received': 'ESXi Received',
  'ESXi Transmitted': 'ESXi Transmitted',
  'Host CPU': 'Host CPU',
  'Host Memory': 'Host Memory',
  'Host CPU Ready': 'Host CPU Ready',
  'Host Disk Read Throughput': 'Host Disk Read Throughput',
  'Host Disk Write Throughput': 'Host Disk Write Throughput',
  'Host Disk Read Latency': 'Host Disk Read Latency',
  'Host Disk Write Latency': 'Host Disk Write Latency',
  'Host Disk Read IO': 'Host Disk Read IO',
  'Host Disk Write IO': 'Host Disk Write IO',
  'Host Network Received': 'Host Network Received',
  'Host Network Transmitted': 'Host Network Transmitted',
  'VMware CPU': 'VMware CPU',
  'VMware Memory': 'VMware Memory',
  'VMware Disk Read IO': 'VMware Disk Read IO',
  'VMware Disk Write IO': 'VMware Disk Write IO',
  'VMware Disk Read Throughput': 'VMware Disk Read Throughput',
  'VMware Disk Write Throughput': 'VMware Disk Write Throughput',
  'VMware Disk Read Latency': 'VMware Disk Read Latency',
  'VMware Disk Write Latency': 'VMware Disk Write Latency',
  'Network Drop In': 'Network Drop In',
  'Network Drop Out': 'Network Drop Out',
  'CPU': 'CPU',
  'Memory Usage Percent': 'Memory Usage Percent',
  'VM CPU': 'VM CPU',
  'VM Memory': 'VM Memory',
  'VM Disk Read Latency': 'VM Disk Read Latency',
  'VM Disk Write Latency': 'VM Disk Write Latency',
  'VM Disk Read IO': 'VM Disk Read IO',
  'VM Disk Write IO': 'VM Disk Write IO',
  'VM Disk Read Throughput': 'VM Disk Read Throughput',
  'VM Disk Write Throughput': 'VM Disk Write Throughput',
  'Percent Memory Usage': 'Percent Memory Usage',
  'Disk Used Megabytes': 'Disk Used Megabytes',
  'Disk Read Throughput Persec': 'Disk Read Throughput Persec',
  'Disk Write Throughput Persec': 'Disk Write Throughput Persec',
  'Disk Read IO Persec': 'Disk Read IO Persec',
  'Disk Write IO Persec': 'Disk Write IO Persec',
  'Disk Read Latency Percent': 'Disk Read Latency Percent',
  'Disk Write Latency Percent': 'Disk Write Latency Percent',
  'Network Received Packet Persec': 'Network Received Packet Persec',
  'Network Sent Packet Persec': 'Network Sent Packet Persec',
  'Network Error In': 'Network Error In',
  'Network Error Out': 'Network Error Out',
  'Windows Version': 'Windows Version',
  'Max CPU next 1 week': 'Max CPU next 1 week',
  'Max Memory next 1 week': 'Max Memory next 1 week',
  'Max Load5 next 1 week': 'Max Load5 next 1 week',
  'Max CPU Ready next 1 week': 'Max CPU Ready next 1 week',
  'Max CPU Next Week': 'Max CPU Next Week',
  'Max Memory Next Week': 'Max Memory Next Week',
  'Max CPU Ready Next Week': 'Max CPU Ready Next Week',
  'Max Disk Read IO Next Week': 'Max Disk Read IO Next Week',
  'Max Disk Write IO Next Week': 'Max Disk Write IO Next Week',
  'Server Type': 'Server Type',
  'Byte Used': 'Byte Used',
  'RB Byte': 'RB Byte',
  'Raw Byte Used': 'Raw Byte Used',
  'WR Byte': 'WR Byte',
  'Save': 'Save',
  'Cancel': 'Cancel',
  'Edit Rule': 'Edit Rule',
  'Add Rule': 'Add Rule',
  'Threshold is required.': 'Threshold is required.',
  'Threshold should be a number.': 'Threshold should be a number.',
  'Threshold should be positive.': 'Threshold should be positive.',
  'Threshold integer part should be less than 17 characters.': 'Threshold integer part should be less than 17 characters.',
  'Threshold float part should be less than 2 characters.': 'Threshold float part should be less than 2 characters.',
  'Threshold for': 'Threshold for',
  'should be integer': 'should be integer',
  'Current password': 'Current password',
  'New Password': 'New Password',
  'Enter new password': 'Enter new password',
  'Confirm New Password': 'Confirm New Password',
  'Change': 'Change',
  'Name': 'Name',
  'A valid password is required, minimum length of 4': 'A valid password is required, minimum length of 4',
  'Retype new password': 'Retype new password',
  'Password should match New Password': 'Password should match New Password',
  'Required': 'Required',
  'Not changed, type to change password': 'Not changed, type to change password',
  'Required, min 3 characters': 'Required, min 3 characters',
  'Admin': 'Admin',
  'ADMIN': 'ADMIN',
  'Username': 'Username',
  'Password': 'Password',
  'Retype Password': 'Retype Password',
  'Delete': 'Delete',
  'Next 1 day': 'Next 1 day',
  'Next 7 days': 'Next 7 days',
  'Next 14 days': 'Next 14 days',
  'Next 30 days': 'Next 30 days',
  'Next 90 days': 'Next 90 days',
  'Disk Read Bytes/sec': 'Disk Read Bytes/sec',
  'Disk Write Bytes/sec': 'Disk Write Bytes/sec',
  'Disk Reads/sec': 'Disk Reads/sec',
  'Disk Write/sec': 'Disk Write/sec',
  '% Disk Read Time': '% Disk Read Time',
  '% Disk Write Time': '% Disk Write Time',
  'All host groups': 'All host groups',
  'All disk groups': 'All disk groups',
  'Host': 'Host',
  'Disk': 'Disk',
  'Delete User': 'Delete User',
  'Are you sure to delete this user?': 'Are you sure to delete this user?',
  'Ok': 'Ok',
  'User has been deleted': 'User has been deleted',
  'Rule has been deleted': 'Rule has been deleted',
  'Password has been updated.': 'Password has been updated.',
  'Group has been updated.': 'Group has been updated.',
  'Group has been saved.': 'Group has been saved.',
  'Group has been deleted': 'Group has been deleted',
  'Are you sure to delete this rule?': 'Are you sure to delete this rule?',
  'Are you sure you want to delete the selected item??': 'Are you sure you want to delete the selected item??',
  'Delete Group': 'Delete Group',
  'Delete Rule': 'Delete Rule',
  'Read Throughput': 'Read Throughput',
  'Write Throughput': 'Write Throughput',
  'Write Latency': 'Write Latency',
  'Read Latency': 'Read Latency',
  'Series': 'Series',
  'Transmitted': 'Transmitted',
  '% User Time': '% User Time',
  '% Memory Usage': '% Memory Usage',
  'Disk Usage': 'Disk Usage',
  'This panel is for simulating disk failure prediction.': 'This panel is for simulating disk failure prediction.',
  "By tuning a disk's SMART data and performance from this panel,": "By tuning a disk's SMART data and performance from this panel,",
  'DiskProphet will generate a new disk failure prediction from the tunning.': 'Federator.ai will generate a new disk failure prediction from the tunning.',
  'We call it "simulation" because the prediction is not generated': 'We call it "simulation" because the prediction is not generated',
  'from the actual data collected from a disk,rather from the tuning.': 'from the actual data collected from a disk,rather from the tuning.',
  'Please click the "Simulate" button when the configuration is done.': 'Please click the "Simulate" button when the configuration is done.',
  'Click the "Restore" button to restore to the real prediction.': 'Click the "Restore" button to restore to the real prediction.',
  'If a simulation is not restored, it will be overwritten by the next prediction round.': 'If a simulation is not restored, it will be overwritten by the next prediction round.',
  'CPU/Memory': 'CPU/Memory',
  'Disk Performance': 'Disk Performance',
  'Is Simulated': 'Is Simulated',
  'In': 'In',
  'Out': 'Out',
  'Zoom In': 'Zoom In',
  'Storage I/O': 'Storage I/O',
  'Network': 'Network',
  'Correlation': 'Correlation',
  'Utilization': 'Utilization',
  'VM Storage Latency': 'VM Storage Latency',
  'VM Storage Throughput': 'VM Storage Throughput',
  'ESXi Storage Latency': 'ESXi Storage Latency',
  'ESXi Storage Throughput': 'ESXi Storage Throughput',
  'Disks that will last more than 6 weeks': 'Disks that will last more than 6 weeks',
  'Disks that will fail within 6 weeks': 'Disks that will fail within 6 weeks',
  'Disks that will fail within 2 weeks': 'Disks that will fail within 2 weeks',
  'General': 'General',
  'Uptime': 'Uptime',
  'Notes': 'Notes',
  'Location': 'Location',
  'Update Location': 'Update Location',
  'empty': 'empty',
  'Close': 'Close',
  'Select tags...': 'Select tags...',
  'Select': 'Select',
  'Capacity Usage': 'Capacity Usage',
  'Description': 'Description',
  'eg: Reserved Hosts': 'eg: Reserved Hosts',
  'Information about group': 'Information about group',
  'Fixed': 'Fixed',
  'Smart': 'Smart',
  'Parent Group': 'Parent Group',
  'Show only selected': 'Show only selected',
  'Match': 'Match',
  'All Conditions': 'All Conditions',
  'Any Condition': 'Any Condition',
  'Conditions': 'Conditions',
  'All Hosts': 'All Hosts',
  'Tag': 'Tag',
  'equal to': 'equal to',
  'not equal to': 'not equal to',
  'contains': 'contains',
  'not contains': 'not contains',
  'starts with': 'starts with',
  'ends with': 'ends with',
  'Field': 'Field',
  'Operator': 'Operator',
  'Value': 'Value',
  'SMART': 'SMART',
  'ALL': 'ALL',
  'ANY': 'ANY',
  'Cluster Name': 'Cluster Name',
  'MONs': 'MONs',
  'Pools': 'Pools',
  'OSDs': 'OSDs',
  'OSD Used': 'OSD Used',
  'Max OSD Used next 1 week': 'Max OSD Used next 1 week',
  'Cluster OSD Bytes Used %': 'Cluster OSD Bytes Used %',
  'Used Bytes': 'Used Bytes',
  'Raw Used Bytes': 'Raw Used Bytes',
  'IO Bytes': 'IO Bytes',
  'OP IO Latency': 'OP IO Latency',
  'OP IO Bytes': 'OP IO Bytes',
  'OP Read': 'OP Read',
  'OP Write': 'OP Write',
  'OP Read Latency': 'OP Read Latency',
  'OP Write Latency': 'OP Write Latency',
  'OP Read Out Bytes': 'OP Read Out Bytes',
  'OP Write In Bytes': 'OP Write In Bytes',
  'Ceph Hosts': 'Ceph Hosts',
  'Ceph Clusters': 'Ceph Clusters',
  'Cluster': 'Cluster',
  'Timeline': 'Timeline',
  'NOW': 'NOW',
  'CUSTOM': 'CUSTOM',
  'Event List': 'Event List',
  'Event Name': 'Event Name',
  'Email Settings': 'Email Settings',
  'Edit Email Settings': 'Edit Email Settings',
  'Add Email Settings': 'Add Email Settings',
  'Delete Email Settings': 'Delete Email Settings',
  'Subject': 'Subject',
  'Message': 'Message',
  'ToEmail': 'To',
  'AppDynamic Event': 'AppDynamic Event',
  'Subject is required.': 'Subject is required.',
  'Subject length should be less than 60 characters.': 'Subject length should be less than 60 characters.',
  'Message length should be less than 1000 characters.': 'Message length should be less than 1000 characters.',
  'Email is required.': 'Email is required.',
  'Email should be less than 60 characters.': 'Email should be less than 60 characters.',
  'Email format is wrong.': 'Email format is wrong.',
  'Description length should be less than 60 characters.': 'Description length should be less than 60 characters.',
  'There are some errors in email settings form': 'There are some errors in email settings form',
  'Are you sure to delete this email settings?': 'Are you sure to delete this email settings?',
  'Cannot get email settings data. Error:': 'Cannot get email settings data. Error: {{ message }}',
  'Add email settings failed, Error:': 'Add email settings failed, Error:',
  'Email settings has been deleted': 'Email settings has been deleted',
  'Please select a disk to simulate': 'Please select a disk to simulate',
  'Simulate successfully': 'Simulate successfully',
  'Add rule failed': 'Add rule failed',
  'There are some errors in add rule form': 'There are some errors in add rule form',
  'There are some errors in edit rule form': 'There are some errors in edit rule form',
  'Language': 'Language',
  'Network Error': 'Network Error',
  'Error In': 'Error In',
  'Error Out': 'Error Out',
  'Network Error (Error In)': 'Network Error (Error In)',
  'Network Error (Error Out)': 'Network Error (Error Out)',
  'Group Name': 'Group Name',
  'kapacitor.smtp.service.port.note': "If the port is set to 465, SSL/TLS will be used for connections; if the port isn't set to 465 but STARTTLS is supported by the SMTP server, STARTTLS will be used for connections; otherwise non-secure connections will be applied.",
  'AllDisk': 'All Disk',
  'AllHost': 'All Host',
  'No Data To Show': 'No Data To Show',
  'State': 'State',
  'true': 'online',
  'false': 'offline'
}

export default {
  en
}
